### ISSUE TITLE
axios vulnerability

### ISSUE THREAD

**Issue by Mvbraathen** [acacode/swagger-typescript-api#101]
Hi there! 

Just a friendly reminder to upgrade axios due to vulnerabilities :) 
![image](https://user-images.githubusercontent.com/16756739/103631956-ee0a7d00-4f43-11eb-8a89-898fc736b0c0.png)
Best regards, 
Mvbraathen

**Comment by js2me** [comment]
Hello @Mvbraathen !

Please open PR if you can, use `master` branch

**Comment by Mvbraathen** [comment]
Done 👍
#102

**Comment by js2me** [comment]
@Mvbraathen  thank you for issue and PR!
