### ISSUE TITLE
additionalProperties: true

### ISSUE THREAD

**Issue by brookjordan** [acacode/swagger-typescript-api#103]
When a swagger model contains `additionalProperties: true` I think that the created TypeScript interfaces should deal with this somehow.
Maybe by adding `[key: string]?: any,`, at least as a stop-gap.

**Comment by js2me** [comment]
Hello @brookjordan  
I think it should be added at next release (4.0.0)  (`next` branch)

**Comment by js2me** [comment]
Good evening or morning @brookjordan ! 🙂   
Release 4.0.0 should support `additionalProperties: true`, but use 4.0.2 (fixed a couple critical bugs)   
Thanks for this issue, reopen if you won't see expected result!  

And also be careful if you use custom templates option with mustache templates, currently templates written on `ETA`
