### ISSUE TITLE
Allow baseUrl to be set dynamically

### ISSUE THREAD

**Issue by kerly** [acacode/swagger-typescript-api#106]
As a developer I'd like to be able to dynamically point the client's baseUrl at a previously unspecified url. This is useful because many CI/CD pipelines dynamically generates urls and it would be useful to dynamically set the url without re-generating the client code.   
I could see this done as an environment variable that sets the baseUrl, and some switch in the command to insert the environment variable.   
Example:   
```
npx swagger-typescript-api --dynamic-url
```
```
public baseUrl: string = process.env.CLIENT_BASE_URL;
```

**Comment by js2me** [comment]
Hello @kerly !   
Thanks for issue  
You can use custom templates for this feature  
Just replace this template's line to what's you need:  
https://github.com/acacode/swagger-typescript-api/blob/master/src/templates/defaults/http-client.mustache#L37  
```
public baseUrl: string = "{{apiConfig.baseUrl}}";
```

**Comment by LoLei** [comment]
For me, overwriting this entire template for a single change seems like a hassle. I too, would prefer a command line option.
