### ISSUE TITLE
Underscores are omitted from enum keys

### ISSUE THREAD

**Issue by eolant** [acacode/swagger-typescript-api#108]
Starting from version 1.12 enum values like this `ERROR_NO_KEY` converted to `ERRORNOKEY = "ERROR_NO_KEY"` which is incorrect and ideally should remain the same.

**Comment by js2me** [comment]
Hello @eolant !   
I think underscores shouldn't be omitted only when all words in upper case , yes?

**Comment by js2me** [comment]
Because sometimes swagger schema generators can create very strange schema with definitions like `Pick_UserType.Exclude_keyofUserType.id-or-_id__` (from `tsoa`)

**Comment by eolant** [comment]
@js2me yeah, I assume this would be the case in most situations, enum schema values would be uppercase with underscores

**Comment by js2me** [comment]
Hello @eolant !   
Issue fixed in 4.3.0
