### ISSUE TITLE
Self signed certificate error

### ISSUE THREAD

**Issue by kel666** [acacode/swagger-typescript-api#114]
My dev machine use swagger endpoint on https with a self-signed certificate.
If I run swagger-typescript-api I get this error:

`(node:14680) UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1498:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:940:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:698:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on
unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Would be possibile to add an options to accept also self-signed certiificate?

Tnx
Fabio

**Comment by js2me** [comment]
Hello @kel666 !
Thanks for this issue
Is this issue based on fetch swagger schema with using self significant certificate?

**Comment by kel666** [comment]
Mmmm don't exactly what you mean, swagger is running on a IIS server.
This happens when I run

`npx swagger-typescript-api -p {internal_url_with_https} `

tnx
Fabio

**Comment by js2me** [comment]
I think it is problem of axios tool, which I use for download swagger schema by url \ `-p`    

@kel666  may be add option `--cert`  which has been used for certificate path ?

**Comment by kel666** [comment]
It's an options but it wolud be uncomforable, since one should download the certificate and point to it.
Don't you like the idea of having an options bypassing SSL strict?

**Comment by js2me** [comment]
@kel666 Please open PR with ignoring SSL strict if you can! Use the `next` branch for changes

**Comment by js2me** [comment]
As quick solution I think this can be helped to you  
https://github.com/axios/axios/issues/535#issuecomment-58819624

**Comment by kel666** [comment]
Just created the PR let me know if is ok

**Comment by js2me** [comment]
Thank you for issue and PR @kel666 !   
option `--disableStrictSSL` added in `swagger-typescript-api@4.0.3`
