### ISSUE TITLE
'prettier-plugin-organize-imports' affects a dependent project

### ISSUE THREAD

**Issue by mrfratello** [acacode/swagger-typescript-api#134]
Hi. I'm using swagger-typescript-api v4. 0. 4 as a dev dependency for the project.

The project uses 'prettier' with a specific configuration. The swagger-typescript-api sets the prettier plugin 'prettier-plugin-organize-imports' as dependencies. This plugin does not require any configuration and will work directly after installation. I tried disabling this plugin but couldn't. My team doesn't want to use this add-on for prettier.

Is it possible to move "prettier-plugin-organize-imports" to devDependencies/peerDependencies or delete it? 
As an option, I suggest using another plugin with the configuration in prettierrc, for example https://github.com/trivago/prettier-plugin-sort-imports. 

Or will anybody suggest a workaround for switch-off 'prettier-plugin-organize-imports'?

**Comment by js2me** [comment]
Hello @mrfratello !
I will remove this plugin in next release, but for now as quick solution you can generate swagger API module with `generateApi()` function exported from this package with NodeJS.   
`generateApi()` takes generate generate API configuration object which have `prettier` property (`pretter configuration`)


```ts
const { generateApi } = require("swagger-typescript-api")

generateApi({
  url,
  output,
  prettier: {
    plugins:[],
  }
})
```

Hope that helps

**Comment by mrfratello** [comment]
Good news, I'll be waiting for the next release. Unfortunately, this plugin affects all project files (not just generated files) if prettier is used in the project.

**Comment by js2me** [comment]
@mrfratello Did you try to add `plugins:[]` section for project prettier rc file?

**Comment by mrfratello** [comment]
@js2me Ha-ha. The plugins stopped loading if provide at least one valid path value (not `node_modules`) in `pluginSearchDirs` property in prettierrc:

```
{
   pluginSearchDirs: ["./src"]
}
```

**Comment by js2me** [comment]
Good day @mrfratello!   
`prettier-plugin-organize-imports` has been removed in 4.0.5 version!   
If you still get this problem please reopen issue.
