### ISSUE TITLE
Output folder creation

### ISSUE THREAD

**Issue by Rinta01** [acacode/swagger-typescript-api#137]
Hey! Firstly, thanks for this awesome tool! Helped a lot on my project.

I wanted to propose a change: when you specify the "-o" (output directory) option it is not created when it doesn't exist. I know it's not really a big deal for many users but it would be a great QoL change!

**Comment by js2me** [comment]
Hello @Rinta01 !   
Yes, I know about that problem, will do at next minor release

**Comment by js2me** [comment]
Hello @Rinta01!   
This feature should be added in 4.1.0, thank you!

**Comment by Rinta01** [comment]
@js2me Thanks! Good stuff!
