### ISSUE TITLE
CLI silently fails if the directory to put new files in doesn't exist yet

### ISSUE THREAD

**Issue by Styn** [acacode/swagger-typescript-api#141]
When a directory is defined with the `-o` option that doesn't exist, instead of it being created the script just stops and indicates success.

A workaround is to add something like `npx make-dir-cli your/path` before starting `swagger-typescript-api`

**Comment by js2me** [comment]
Hello @Styn   
This bug should be fixed in 4.3.0   
Please reopen issue if you still got this problem
