### ISSUE TITLE
Templates for axios with the ability to pass a custom instance

### ISSUE THREAD

**Issue by msklvsk** [acacode/swagger-typescript-api#142]
Have someone by any chance created a template that uses an axios instance instead of fetch? or are there any plans to implement it in-project? Just asking before starting to implement one myself.

**Comment by js2me** [comment]
I use templates with `ky` and `qs` and I think it is not a problem to create templates for axios http client

**Comment by js2me** [comment]
I think it is not needed to implementing in project because it will not be a silver bullet for everyone

**Comment by msklvsk** [comment]
It turned out pretty easy. If don’t plan to support axios in this project then I guess this issue can be closed...
```diff
index 2a371ca..140095a 100644
--- a/templates/default/data-contracts.eta
+++ b/templates/default/data-contracts.eta
@@ -1,3 +1,5 @@
+import { default as defaultAxios, AxiosInstance, Method } from 'axios'
+
 <%
   const { modelTypes, utils } = it;
   const { formatDescription, require } = utils;
diff --git a/templates/default/http-client.eta b/templates/default/http-client.eta
index 616f8f3..fc75d26 100644
--- a/templates/default/http-client.eta
+++ b/templates/default/http-client.eta
@@ -47,7 +47,7 @@ export class HttpClient<<%~ apiConfig.generic.map(g => `${g.name} = unknown`).jo
         referrerPolicy: 'no-referrer',
     }
 
-    constructor(apiConfig: ApiConfig<<%~ apiConfig.generic.map(g => g.name).join(', ') %>> = {}) {
+    constructor(apiConfig: ApiConfig<<%~ apiConfig.generic.map(g => g.name).join(', ') %>> = {}, private axios: AxiosInstance = defaultAxios) {
         Object.assign(this, apiConfig);
     }
 
@@ -119,7 +119,7 @@ export class HttpClient<<%~ apiConfig.generic.map(g => `${g.name} = unknown`).jo
         body?: any,
         bodyType?: BodyType,
         secureByDefault?: boolean,
-    ): <% if (generateResponses) { %>TPromise<HttpResponse<T, E>><% } else { %>Promise<HttpResponse<T>><% } %> => {
+    ) => {
         const requestUrl = `${this.baseUrl}${path}`;
         const secureOptions = (secureByDefault || secure) && this.securityWorker ? this.securityWorker(this.securityData) : {};
         const requestOptions = {
@@ -128,10 +128,10 @@ export class HttpClient<<%~ apiConfig.generic.map(g => `${g.name} = unknown`).jo
             body: body ? this.bodyFormatters[bodyType || BodyType.Json](body) : null,
         }
 
-        return fetch(requestUrl, requestOptions).then(async response => {
-            const data = await this.safeParseResponse<T, E>(response);
-            if (!response.ok) throw data
-            return data
+        return this.axios.request<T>({
+            url: requestUrl,
+            ...requestOptions,
+            method: requestOptions.method as Method
         })
     }
 }
```

**Comment by js2me** [comment]
@msklvsk thanks for sharing templates changes, it can help someone who wants to use axios!

**Comment by Ahriana** [comment]
ty, i needed this. mybe native support would be nice. thanks either way @msklvsk

**Comment by mixalbl4-127** [comment]
@js2me +1 this is a better for frontend devs, maybe need to add native `--axios` option for it?

**Comment by js2me** [comment]
@msklvsk @mixalbl4-127 @Ahriana    
If it really needed I'll add `--axios` option at the next patch release!

**Comment by mixalbl4-127** [comment]
My varian of dirty hack for `axios` for ` --modular --single-http-client"`, works for me but without `ContentType` and other feautures :(

```typescript
import { Api as OriginalApi } from "@/api/Api";
import { FullRequestParams } from "@/api/http-client";
const fake: any = {
    request: (reqParams: FullRequestParams) =>
        axiosInstance.request({
            url: reqParams.path,
            method: reqParams.method as Method,
            params: reqParams.query,
            data: reqParams.body
        })
};
const Api = new OriginalApi(fake);
export { Api };
```

One more think, please make `--single-http-client` works with `axios` too, for ability to send custom `axiosInstance`

**Comment by js2me** [comment]
@msklvsk @mixalbl4-127   
What do you think about this axios based HttpClient class ?   
https://github.com/acacode/swagger-typescript-api/blob/next/tests/spec/axios/schema.ts#L1471   

Here is current draft template of axios http client   
https://github.com/acacode/swagger-typescript-api/blob/next/templates/base/http-clients/axios-http-client.eta

**Comment by mixalbl4-127** [comment]
надоело по английски)) @js2me 
`toQueryString`/`addQueryParam` это лишняя штука для аксиос, она и так кушает массив/объект и сама что квери что параметры умеет оборачивать
`contentFormatters` так же излишний, по той-же причине что и для квери, аксиос сам видит какой тип в него зашёл и конвертит соответствующе, как в [моём примере выше](https://github.com/acacode/swagger-typescript-api/issues/142#issuecomment-782694440), всё это работает без доп.костылей :)

и да, в аксиос есть нативная поддержка своего `cancelToken`, его стоит оставить в типах.
как раз на днях интересную реализацию с ним сделал https://stackoverflow.com/a/66385063/2051938

**Comment by js2me** [comment]
@mixalbl4-127 Привет :)   
Понял, спасибо! сделаю правки в ПР

**Comment by js2me** [comment]
`--axios` option has been added in 6.0.0 version !   
Thanks everyone for motivation to do that feature!

**Comment by a-pavlov-parc** [comment]
@js2me только что затестил работу с ` --axios --single-http-client`. Вижу, что в методе `request` не используется аргумент `path` и запросы всё время стучатся в `baseUrl`

**Comment by js2me** [comment]
@a-pavlov-parc Спасибо, сейчас выложу фикс

**Comment by js2me** [comment]
+ проблема с format полем еще

**Comment by js2me** [comment]
@a-pavlov-parc  Должно быть исправлено в 6.1.1 версии
