### ISSUE TITLE
Client generation for `Content-Type: application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by Larox** [acacode/swagger-typescript-api#146]
Hey,

I've encountered an issue when trying to create the API Client and data models from my swagger file. This is happening when the `Content-Type` of my API is `application/x-www-form-urlencoded`. Currently, it is being created as Json or form data when a query string is needed as the body and for this reason, when using the client it is failing.

Here is the definition of that specific endpoint in my `swagger.json` file:

```json
"/auth/login": {
    "post": {
        "responses": {
            "500": {
                "description": "Internal server error."
            },
            "400": {
                "description": "Validation error."
            },
            "401": {
                "description": "Email or password does not match"
            },
            "200": {
                "description": "Login succeeded."
            }
        },
        "summary": "Authenticate an existing user and return an access token",
        "operationId": "post_auth_api",
        "parameters": [
            {
                "name": "email",
                "in": "formData",
                "type": "string",
                "format": "email",
                "required": true
            },
            {
                "name": "password",
                "in": "formData",
                "type": "string",
                "required": true
            }
        ],
        "security": [],
        "consumes": [
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        ],
        "tags": [
            "auth"
        ]
    }
}
```

And the code generated: 

```ts
export class Auth extends HttpClient {
  postAuthApi = (data: { email: string; password: string }, params?: RequestParams) =>
    this.request<any, any>(`/auth/login`, "POST", params, data, BodyType.FormData, true);
    ...
    }
```

I'm using this command for generating the models and Is there a configuration I am missing for this case? 

`npx swagger-typescript-api -p https://myapi.com/v1/swagger.json -o ./src/apiClient --modular`

**Comment by js2me** [comment]
Hello @Larox !   
Thanks for this issue, will fix it in next release!

**Comment by js2me** [comment]
@Larox what's happening when you create a request with this method `postAuthApi` ?   
HttpClient try to convert FormData to json ?

**Comment by Larox** [comment]
Hey @js2me, when I create a request with `postAuthApi` the FormData is being generated correctly, the issue is that the API requires `Content-Type=application/x-www-form-urlencoded` and expects to receive a Query String, not a FormData.

I tried editing the `swagger.json` file:
```diff 
"consumes": [
            "application/x-www-form-urlencoded",
-            "multipart/form-data"
        ],
```

With this update, the `postAuthApi` method uses `BodyType.JSON`. Formating the request body to JSON. Meanwhile, I was expecting a request body formatted like a Query String.

Let me know if extra information is needed.

**Comment by js2me** [comment]
Hello @Larox !   
This problem should be fixed in 4.3.0   
Please reopen issue if you still got this bug

**Comment by Larox** [comment]
Hey, @js2me Thanks for fixing this. I just tried it out and I'm still having some issues:

- When generating the client, using:
```bash
npx swagger-typescript-api@4.3.0 -p https://myapi.com/v1/swagger.json -o ./src/apiClient --modular
``` 
It is still taking the `form-data` body type. The swagger.json is the same I posted above.

I tried it again with a `testSwagger.json` file where I removed manually the "multipart/form-data" and it worked, but using a static file is not an option since the API I'm using changes continuously.

- The request is being generated with a query string now which is great! But it is being passed as a query parameter, not as a body request. 

This is the cUrl request swagger provides: 
```bash
curl -X POST "https://myapi.com/v1/auth/login" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "email=foo%40bar.com&password=strongpassword"
```
And this is how it is currently being created:
```bash
curl 'https://myapi.com/v1/auth/login?email=foo%40bar.com&password=strongpassword' -H 'Content-Type: application/x-www-form-urlencoded'
```

**Comment by Larox** [comment]
I'm not able to reopen the issue, please re-open it when you can.

**Comment by js2me** [comment]
Hello @Larox!  
It is my mistake, try to quick fix that now

**Comment by js2me** [comment]
https://github.com/acacode/swagger-typescript-api/blob/next/tests/schemas/v2.0/another-example.json#L266   
https://github.com/acacode/swagger-typescript-api/blob/next/tests/generated/v2.0/another-example.ts#L364

**Comment by js2me** [comment]
Hello @Larox!   
Thank you for issue, should be fixed in 4.4.0

**Comment by Larox** [comment]
@js2me Thanks for fixing this so fast. I'll try it out again!

**Comment by s-titov** [comment]
@js2me same issue with axios
