### ISSUE TITLE
The HttpResponse type is no longer exported from http-client

### ISSUE THREAD

**Issue by Styn** [acacode/swagger-typescript-api#161]
When using this library in conjunction with something like redux-saga, you would usually use the `call` method provided by redux-saga. This method by default returns any, so I usually type it to something like `HttpResponse<ResponseData, x>`.
However due to a recent change, this is no longer possible. If this is intentional, it would be good to know how to handle this (common) scenario.

I put a comment on the line change that breaks this:

This makes it hard to type responses in code that uses the HttpClient.
(For example when using this with the `call` method of `redux-saga` where you need to type the expected response yourself, since `call` uses `any`.

_Originally posted by @Styn in https://github.com/acacode/swagger-typescript-api/pull/149#r576015387_

**Comment by js2me** [comment]
Hello @Styn ! You're too late with comment at 5.0.0 PR :)   
I'll fix that at next release 5.1.0 (in, like, 20 minutes)

**Comment by Styn** [comment]
> Hello @Styn ! You're too late with comment at 5.0.0 PR :)
> I'll fix that at next release 5.1.0 (in, like, 20 minutes)

I suddenly got a failing build on the buildserver and went hunting for what changed.
Just wanted to make the maintainers' work a bit easier by exactly pointing out what caused my problem!

**Comment by js2me** [comment]
@Styn I've revert back the export HttpResponse from generated Api file, thank you for report!
