### ISSUE TITLE
Linter disable rules is not working

### ISSUE THREAD

**Issue by Haritaso** [acacode/swagger-typescript-api#164]
Linter disable rules in `src/filePrefix.js` was changed in #157, but this doesn't work.

See:
https://eslint.org/docs/user-guide/configuring/rules#using-configuration-comments-1
https://palantir.github.io/tslint/usage/rule-flags/

**Comment by js2me** [comment]
Hello @Haritaso ! Thanks for catching this problem, fix at next minor release!

**Comment by js2me** [comment]
@Haritaso or open PR if you can!

**Comment by js2me** [comment]
@Haritaso fixed in 5.1.2 version!   
Thanks!
