### ISSUE TITLE
Allow overriding only one template

### ISSUE THREAD

**Issue by Nihisil** [acacode/swagger-typescript-api#166]
Right now if you specify `--templates` option it makes the tool load all templates from the provided folder.

And if there are missing files in this folder it raises an error. 

I think it would be helpful to add fallback here and if in the provided folder template is not exists to load it from the default template folder.

**Comment by js2me** [comment]
Hello @Nihisil , thanks for this issue!    
Yes, it is a good idea to customize only one template

**Comment by js2me** [comment]
5.1.7 Release has partial fix for this issue (Allow to remove all unused templates except templates used in ETA `includeFile()`)

**Comment by js2me** [comment]
It will fixed in 6.0.0 major version

**Comment by js2me** [comment]
@Nihisil it should be fixed in 6.0.0  
Thank you for issue !
