### ISSUE TITLE
ContentType.Json doesn't set the content type header correctly

### ISSUE THREAD

**Issue by Styn** [acacode/swagger-typescript-api#171]
Recently (I think since 5.0.0) requests (I've seen it happen with POST and PUT) that define ContentType.Json don't correctly set the content-type header.
It's set to `Content-Type: text/plain;charset=UTF-8`

A workaround is possible by setting the content-type by hand via `RequestParams` and setting the `Content-Type` to `application/json` manually.

**Comment by js2me** [comment]
Hello @Styn !  
Can you share part of generated code and related part of schema ?

**Comment by Styn** [comment]
Generated code:
`  /**
   * No description
   *
   * @tags Profiles
   * @name ProfilesPut
   * @summary Update an existing Profile.
   * @request PUT:/bp-profiles/v1/profiles/{id}
   */
  profilesPut = (id: string, data: ProfileDto, params: RequestParams = {}) =>
    this.request<ProfileDto, any>({
      path: `/bp-profiles/v1/profiles/${id}`,
      method: "PUT",
      body: data,
      type: ContentType.Json,
      ...params,
    });`

Scheme: 
`"/bp-profiles/v1/profiles/{id}": {
      "get": {
        "tags": [
          "Profiles"
        ],
        "summary": "Retrieve a Profile.",
        "operationId": "Profiles_GetProfile",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProfileDto"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Profiles"
        ],
        "summary": "Update an existing Profile.",
        "operationId": "Profiles_Put",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "guid"
            },
            "x-position": 1
          },
          {
            "name": "If-Match",
            "in": "header",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 3
          }
        ],
        "requestBody": {
          "x-name": "profileDto",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProfileDto"
              }
            }
          },
          "required": true,
          "x-position": 2
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProfileDto"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Profiles"
        ],
        "summary": "Logically delete a Profile.",
        "operationId": "Profiles_Delete",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          }
        }
      }
    },`

**Comment by js2me** [comment]
If that start happening after 5.0.0 release I think it based on change this code line 🤔   
https://github.com/acacode/swagger-typescript-api/pull/149/files#diff-dcf49af463005acec67cb1b99a5414c057eb08e62f286e701ea50713cd2b1235L41   

It removes setting globally Content-Type header because it brokes all other requests

**Comment by js2me** [comment]
@Styn thank you!

**Comment by js2me** [comment]
@Styn did you to use 5.1.4 version ?

**Comment by Styn** [comment]
Your link doesn't link to a specific line, but do you mean the removal of line 45 in `templates/default/http-client.eta`?
Indeed it seems the content type was set to `application/json` by default.

I used 5.1.3, I'll try again with 5.1.4.

**Comment by Styn** [comment]
@js2me I actually updated to 5.1.3 before logging this issue because it was the most recent version according to github releases.
I took a look at the diff with 5.1.4 and this does look like it will fix it.

After testing: It is indeed fixed in 5.1.4

**Comment by js2me** [comment]
@Styn thanks for this issue :)
