### ISSUE TITLE
ContentType.FormData no longer sets the correct boundary

### ISSUE THREAD

**Issue by Styn** [acacode/swagger-typescript-api#172]
This PR: https://github.com/acacode/swagger-typescript-api/pull/168/commits/29d89ec74bfc1598c3b05a624efdd9f109051eb4
breaks the boundary setting for FormData.

Right now the header will look like this: `Content-Type: multipart/form-data` instead of something like `Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryUAzmDsnaGSk1qaI3`

**Comment by js2me** [comment]
Hello @Styn !  
Thanks for this issue, can you fix that problem and create PR ?

**Comment by js2me** [comment]
Or if not, don't worry I'll fix that but I need a bit more time

**Comment by Styn** [comment]
I'll have a PR up soon

**Comment by js2me** [comment]
@Styn fixed in 5.1.5, thank you!
