### ISSUE TITLE
The contentFormatter for ContentType:Json does not correctly format strings

### ISSUE THREAD

**Issue by Styn** [acacode/swagger-typescript-api#176]
When sending a string as json, it should by json.stringified, otherwise the backend is not able to parse it correctly.

I'll create a PR for this

**Comment by js2me** [comment]
Hello @Styn ! Thanks for your contribution !

**Comment by js2me** [comment]
@Styn please, use the `next` branch!

**Comment by Styn** [comment]
Oh sorry, I already created it, will try to fix

**Comment by Styn** [comment]
My previous commits seem to also be included in that PR, even though I created a new fork...

**Comment by js2me** [comment]
Fixed in 5.1.6
