### ISSUE TITLE
Bug with typescript perfomance when use flag -r

### ISSUE THREAD

**Issue by mixalbl4-127** [acacode/swagger-typescript-api#182]
I inform you that there is a bug that drastically affects the use of the library when the `-r` mode is enabled: https://github.com/microsoft/TypeScript/issues/42937

It was found by me thanks to your library :)
If possible, you should redo this part of the code until the typescript fixes this problem.

**Comment by js2me** [comment]
@mixalbl4-127 Wow, that's interesting!   
Probably it can happened because of I use `TPromise` type

**Comment by js2me** [comment]
Thank you for issue

**Comment by js2me** [comment]
`TPromise` will be removed at 6.0.0 version. It was the useless type.
