### ISSUE TITLE
[Request]Add prefix or suffix generated types

### ISSUE THREAD

**Issue by the-ult** [acacode/swagger-typescript-api#191]
Would it be possible to add an option to add a prefix or suffix to the generated types to prevent errors like:
```ts
import { Person } from './models/swagger-api.__generated__';
/// => Import declaration conflicts with local declaration of Person
```

E.g.:
`npx swagger-typescript-api ... --suffix=model`

`Person` => `PersonModel`

For example: 
We are trying to use the generated types/interfaces with graphql-codegen, but the naming of the generated types conflict with the already existing (generated) graphql types.

**Comment by js2me** [comment]
Yeah, it's would be a good idea to add `--type-prefix`, `--type-suffix` as CLI options   
I'll start working on this feature request.   
Thanks for issue!

**Comment by the-ult** [comment]
Thanks @js2me awesome work!

👍

**Comment by js2me** [comment]
@the-ult `--type-prefix`, `--type-suffix` options has been added in 6.3.0 version!   
Thank you for a good feature request!

**Comment by paztis** [comment]
My classic usage is to prefix all the interfaces with I, all the types with T and all the enums with E.
Here we've got a unique prefix for this.
Is it possible to enhance typePrefix a bit to support it ?

**Comment by Bargamut** [comment]
> My classic usage is to prefix all the interfaces with I, all the types with T and all the enums with E.
> Here we've got a unique prefix for this.
> Is it possible to enhance typePrefix a bit to support it ?

+1
Seems like it easy to add `--meta-prefix` for that. Just add new PR with tests. It may be interesting to make it. )
