### ISSUE TITLE
Default params to http client

### ISSUE THREAD

**Issue by Nihisil** [acacode/swagger-typescript-api#192]
Is there a way to set up default params for all requests? I didn't find it.

Right now I need to set `{secure: true}` to each request manually, which is can be improved with default params.

**Comment by js2me** [comment]
Hello @Nihisil !   
Which kind of http client are you using ?

**Comment by Nihisil** [comment]
axios

**Comment by js2me** [comment]
@Nihisil thanks for your bug reports!  
This bug should be fixed in 6.2.1 release.  
Please reopen issue if you still have the same problem.

**Comment by Nihisil** [comment]
Thank you for the quick fix!
