### ISSUE TITLE
Can swagger-typescript-api to generate type definition for the API response?

### ISSUE THREAD

**Issue by kamzcgcg** [acacode/swagger-typescript-api#200]
I'm trying to figure out a way to generate type definition for the API response. I'd like to use response types to define my model (i.e. contract) between the server and the client.
So the flow would be like this:
1- Generate API and Request/Response Types using swagger-typescript-api
2- on the server, generate the Response type and return it through the rest API
3- on the client use the API to call the server and receive the response casted directly to the Response type.

Is that doable>

**Comment by js2me** [comment]
Hello @kamzcgcg !   
1. You can use `--route-types`  to generate request/response types  
2. You can use `--templates` option to create this solution or with using `generateApi()` function add custom templates `customTemplates: []`   
3. default usage swagger-typescript-api as I think 🤔

**Comment by kamzcgcg** [comment]
@js2me Thank you for the quick response. This makes sense. On a small tangent. I'm checking the content of data-contracts.ts I noticed that the requests and the responses are interfaces. Do you see any issue if I change the templates to make them classes so that the server and the client use them as is. Can you let me know the logic behind making them interfaces in the first place?
