### ISSUE TITLE
Duplicated method name (already have method,  solve conflict names) issue

### ISSUE THREAD

**Issue by pmbednarczyk** [acacode/swagger-typescript-api#211]
Hello I have two different methods:
![image](https://user-images.githubusercontent.com/16899307/112624739-4871f600-8e2e-11eb-8991-1127fd4c07fb.png)

While generating API i get this warning: 
Module "clientParticipants" already have method "apiV1RoomsParticipantsDetail()"
�  This method has been renamed to "apiV1RoomsParticipantsDetail2()" to solve conflict names.
![image](https://user-images.githubusercontent.com/16899307/112624645-31cb9f00-8e2e-11eb-9e73-c9b1bf1397c1.png)

What is wrong here? How can i fix it?  I dont like these number suffix :).

**Comment by js2me** [comment]
Hello @pmbednarczyk  !   
Thanks for issue!   
You can use `onFormatRouteName` hook to customize route name as you want
Also, you can use `--module-name-index=3`  which needs to separate route on group by path part (3 -> should be `rooms` in your case)

**Comment by pmbednarczyk** [comment]
Thank you :) I used onFormatRouteName to solve this.

**Comment by GMaiolo** [comment]
@pmbednarczyk could you share how you fixed it? Just encountered the same issue and can't work around it!

**Comment by crobinson42** [comment]
@GMaiolo 
<img width="531" alt="image" src="https://github.com/acacode/swagger-typescript-api/assets/5973579/ab425a38-07f7-4d93-adfd-ef71440432fa">

**Comment by wangshaojie98** [comment]
<img width="996" alt="SCR-20240718-kkyt" src="https://github.com/user-attachments/assets/2489abdd-3e4a-4b67-a6f0-bc8c9dbc8832">
@GMaiolo
