### ISSUE TITLE
safeParseResponse breaks on empty response.

### ISSUE THREAD

**Issue by po5i** [acacode/swagger-typescript-api#213]
Hey team!

I have some endpoints that do some logic in the server and just reply with `200` and empty content. In those cases the `safeParseResponse` function breaks when trying to parse an empty body:

![image](https://user-images.githubusercontent.com/1675168/112648349-70099400-8e17-11eb-98d3-0c28505c5a6d.png)

I think the appropriate response from the API should be `204 No Content`. I own the API and I can do such change nevertheless I can see the client is not handling that case either.

Is there a recommended way to handle this outside of the client? Is it feasible to consider handling this case on the client? 

I'd like to hear from you.

**Comment by js2me** [comment]
Hello @po5i !   
Can you share swagger part of this endpoint ?

**Comment by po5i** [comment]
Sure:

```json
    "/company/{company_id}/msa_signing": {
      "parameters": [
        {
          "in": "path",
          "description": "The company identifier",
          "name": "company_id",
          "required": true,
          "type": "integer"
        }
      ],
      "post": {
        "responses": {
          "400": { "description": "Company or Contact not found" },
          "403": {
            "description": "Company is not available for logged in user."
          },
          "401": { "description": "Token is invalid or expired." },
          "200": { "description": "Signing is completed." }
        },
        "summary": "Current user signs a MSA for a Company",
        "operationId": "post_company_msa_signing_api",
        "parameters": [
          {
            "name": "is_downloaded",
            "in": "formData",
            "type": "boolean",
            "description": "Mark this field if the contact downloaded the document"
          }
        ],
        "consumes": [
          "application/x-www-form-urlencoded",
          "multipart/form-data"
        ],
        "tags": ["company"]
      }
    },
```

**Comment by po5i** [comment]
According to Swagger documentation, empty responses should not include the `content` attribute: https://swagger.io/docs/specification/describing-responses/#empty

**Comment by js2me** [comment]
@po5i thanks for this issue!   
Fix that as soon as possible
