### ISSUE TITLE
Changes to 'base' templates are not picked up

### ISSUE THREAD

**Issue by sprotty** [acacode/swagger-typescript-api#217]
I'm trying to modify the base\http-clients\fetch-http-client.eta.

I've copied the template folders (https://github.com/acacode/swagger-typescript-api/tree/master/templates) from GitHub as is and modified the fetch-http-client.eta file.

I'm using the command

`npx swagger-typescript-api -p https://localhost:44328/swagger/v1/swagger.json --disableStrictSSL --templates api\custom-templates\default`

The command line doesn't complain about the templates (if I change the template path I get a warning, so I assume its OK)

    ✨   try to read templates from directory "XXXX\custom-templates\default"
    ☄️    start generating your typescript api`

However the output does not contain my change.

As a test I put a comment at the top of default\api.eta and this appears in the output. But the output from fetch-http-client.eta appears above this (I figured api.eta was the entry point for the templates), basically it seems to be using the original version of the 'base' templates.

Using version 7.0.1

Incidentally, the change I'm trying to make would allow custom error handling without changing the current API. Ideally this could be added to the main templates?

            if (cancelToken) {
                this.abortControllers.delete(cancelToken);
            }

            return this.handleResponse(data);
        });
    };

    protected handleResponse<T = any, E = any>(response: HttpResponse<T, E>): HttpResponse<T, E>{
        if (!response.ok) 
            throw response;
        return response;
    }
}

Then handleResponse can be overridden to throw a custom exception on failure.

**Comment by js2me** [comment]
Hello @sprotty !  
Thanks for issue!   

If you need to customize http client you need to create `http-client.eta` template and put all template from base/http-clients/fetch-http-client.eta   
Take a look at templates in this manual test, I think it can help you   
https://github.com/acacode/swagger-typescript-api/tree/master/tests/spec/templates

**Comment by sprotty** [comment]
OK, figured it out, I need to copy the template 

    templates/base/http-clients/fetch-http-client.eta

and move and rename it to 

    templates/default/http-client.eta

Then point it at the template directory

    templates/default/

Now when I modify the `template templates/default/http-client.eta` my changes are picked up.
