### ISSUE TITLE
TypeScript 3.7.5 error in the strict mode inside addQueryParams method

### ISSUE THREAD

**Issue by genaby** [acacode/swagger-typescript-api#22]
```
private addQueryParams(query: object): string {
    const keys = Object.keys(query);
    return keys.length ? (
      '?' +
      keys.reduce((paramsArray, param) => [
        ...paramsArray,
        param + '=' + encodeURIComponent(query[param])
      ], []).join('&')
    ) : ''
  }
```
[src/templates/client.mustache](https://github.com/acacode/swagger-typescript-api/blob/master/src/templates/client.mustache)

> (parameter) param: string
No overload matches this call.
  Overload 1 of 3, '(callbackfn: (previousValue: string, currentValue: string, currentIndex: number, array: string[]) => string, initialValue: string): string', gave the following error.
    Type 'string[]' is not assignable to type 'string'.
  Overload 2 of 3, '(callbackfn: (previousValue: never[], currentValue: string, currentIndex: number, array: string[]) => never[], initialValue: never[]): never[]', gave the following error.
    Type 'string[]' is not assignable to type 'never[]'.
      Type 'string' is not assignable to type 'never'.ts(2769)
lib.es5.d.ts(1350, 24): The expected type comes from the return type of this signature.
lib.es5.d.ts(1356, 27): The expected type comes from the return type of this signature.

I suggest following code:
```
  private addQueryParams(query: {[key:string]:string|number|boolean}): string {
    const keys = Object.keys(query);
    return keys.length === 0 ? ''
      : '?' + keys.map(key => encodeURIComponent(key) + '=' + encodeURIComponent(query[key])).join('&')
  }
```

**Comment by js2me** [comment]
@genaby Hello! Thanks for your issue!  
Can you attach your `tsconfig.json` file for more information ?

**Comment by genaby** [comment]
Hello @js2me 
```
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "CommonJS",
        "target": "ES6",
        "jsx": "react",
        "experimentalDecorators": true,
        "removeComments": true,
        "strict": true
    },
    "include": ["./src/**/*"]
}
```

**Comment by genaby** [comment]
Also I think that array destruction in the reduce is not very effective since each iteration will create new array each time.

**Comment by js2me** [comment]
@genaby  Do you want create a PR for this ?

**Comment by genaby** [comment]
sure will do (with small changes to pass all tests)
```
private addQueryParams(query: {[key:string]:string|string[]|number|number[]|boolean}): string {
    const keys = Object.keys(query);
    return keys.length === 0 ? ''
      : '?' + keys.map(key => encodeURIComponent(key) + '=' + encodeURIComponent(query[key])).join('&')
  }
```

**Comment by js2me** [comment]
@genaby  as this is Api module which do requests to the server. I think needs to do more flexible solution for developers usage  
input type queries  sometimes will have `{ optionalKey?: string }` and it means that query type should be `Record<string, any>`  or `Record<string, string|string[]|number|number[]|boolean|undefined>` 🤔

**Comment by js2me** [comment]
@genaby thanks for your contribution :)  
Release 1.4.1 at now have this fix
