### ISSUE TITLE
TypeScript error "TS6133: 'E' is declared but its value is never read."

### ISSUE THREAD

**Issue by pmbednarczyk** [acacode/swagger-typescript-api#220]
Hey! :)
In auto-generated http-client.ts this error occurs (look image). Despite there is ```/* eslint-disable */
/* tslint:disable */``` at the top. 

![image](https://user-images.githubusercontent.com/16899307/113413898-f98f0800-93bb-11eb-894e-c7424f95e3e7.png)

My settings:
![image](https://user-images.githubusercontent.com/16899307/113414109-7f12b800-93bc-11eb-87c6-589cbfee2cfc.png)

Any advice how to prevent such error? Do I miss something? 
When I add  underscore prefix to this parameter ```_E``` or ```// @ts-ignore``` above the line with this error it helps. But I cannot do it mannually every time. 

Best regards,
Pawel

**Comment by js2me** [comment]
Hello @pmbednarczyk !   
Thanks for this issue!  
I'll add `@ts-ignore` in the next release   
unused `E` is needed to just look at what server can return in bad responses
