### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by EvgenBabenko** [acacode/swagger-typescript-api#221]
Hello
i have the following schema 
![Screenshot_1](https://user-images.githubusercontent.com/29785853/113477049-0ed16880-9488-11eb-8560-d9c0c230b302.png)

and without any flags, i'm geting the following result (union enums)
![Screenshot_2](https://user-images.githubusercontent.com/29785853/113477077-4213f780-9488-11eb-83d5-8d7bfacb0193.png)

How can i get enums smth like this: 
`export enum DayOfWeek {
  Sunday = "Sunday",
  Monday = "Monday",
  Tuesday = "Tuesday",
  Wednesday = "Wednesday",
  Thursday = "Thursday",
  Friday = "Friday",
  Saturday = "Saturday",
}`

Maybe smth wong in my schema?

**Comment by js2me** [comment]
Hello @EvgenBabenko !   
You need to move out the `fileAttachmentDescriptiveType` from current object schema and paste in `/components/schemas` (for v3) or in `/definitions` (v2 swagger)

**Comment by js2me** [comment]
and in current object schema replace this field to:   
```json
"fileAttachmentDescriptiveType": { "$ref": "#/components/schemas/fileAttachmentDescriptiveType" }
```

**Comment by EvgenBabenko** [comment]
i don't know how to do it, cuz our back-end based on java+spring, and this schema generated automatically

**Comment by EvgenBabenko** [comment]
i don't know how to do it, cuz our back-end based on java+spring, and this schema generated automatically

**Comment by EvgenBabenko** [comment]
Hello again, our back-end haven't found solution how to do it for spring-boot :(

**Comment by EvgenBabenko** [comment]
Hi again, i've found solution for this case
I found all enums with hook `onParseSchema: (originalSchema, parsedSchema) => {}` replaced them to '__GENERATED__#' and generated additional map. After all i found all matches in filestring with regexp and replaced them through additional generated map.
One thing i don't like it in this method, that i didn't find good way how to name enums. For example, if my schema has name fileAttachmentDescriptiveType: "Sunday" | "Monday", so my enum will have name FileAttachmentDescriptiveType, maybe i should rethink logic, how to name enums properly, but i'm not sure that this way is exist

**Comment by EvgenBabenko** [comment]
I'll close the issue, because this bug related to spring-fox https://github.com/springfox/springfox/issues/1738
Thanks
