### ISSUE TITLE
Axios Interceptors

### ISSUE THREAD

**Issue by indapublic** [acacode/swagger-typescript-api#226]
Hello. Thanks for your great library.
Do you have good examples how to use axios interceptors (e.g. refresh token) for generated apis?

**Comment by marko-hologram** [comment]
> 
> 
> Hello. Thanks for your great library.
> Do you have good examples how to use axios interceptors (e.g. refresh token) for generated apis?

I think you currently cannot add axios interceptors since you don't have access to the actual axios instance that is created by code generated by this library (at least I didn't manage to do it).

**Comment by orouz** [comment]
not a great solution, but you can override the `instance` property on `HttpClient` to use your own.

i think it makes sense to pass an actual instance instead of an instance config.

**Comment by indapublic** [comment]
@orouz I just saw recent release with `customFetch` feature 🤔

**Comment by guhyeon** [comment]
1. change httpclient instance to not private 
![image](https://user-images.githubusercontent.com/9765614/115196381-ccb45200-a12a-11eb-8a2f-41e8cb3ebce0.png)

2.
` const api = new Api();
 api.instance.interceptors.response.use(...)
`

**Comment by marko-hologram** [comment]
> 
> 
>     1. change httpclient instance to public
>        ![image](https://user-images.githubusercontent.com/9765614/115196381-ccb45200-a12a-11eb-8a2f-41e8cb3ebce0.png)
> 
> 
> `const api = new Api(); api.instance.interceptors.response.use(...)`

Wouldn't this change be reset back when you use `swagger-typescript-api` again since the file would be generated again? 
You would have to manually update it back to be public. Not that much of a hassle, but something to keep in mind.

**Comment by guhyeon** [comment]
@marko-hologram, You are right. it is always reseted, unless you can use custom templates, successively.

I'm trying to use custom templates, but it is not work well.
so, I'm now change manually every generating. 🤔

**Comment by guhyeon** [comment]
I just successed using template.

make directory "templates" and
make "http-client.eta" file in "templates" directory
and copy paste https://github.com/acacode/swagger-typescript-api/blob/next/templates/base/http-clients/axios-http-client.eta
and change private instance: AxiosInstance; => instance: AxiosInstance;

![image](https://user-images.githubusercontent.com/9765614/115210924-080a4d00-a13a-11eb-9d0e-124f7aa760fa.png)

**Comment by marko-hologram** [comment]
> 
> 
> I just successed using template.
> 
> make directory "templates" and
> make "http-client.eta" file in "templates" directory
> and copy https://github.com/acacode/swagger-typescript-api/blob/next/templates/base/http-clients/axios-http-client.eta
> and paste into "http-client.eta"
> and change private instance: AxiosInstance; => instance: AxiosInstance;
> 
> ![image](https://user-images.githubusercontent.com/9765614/115210924-080a4d00-a13a-11eb-9d0e-124f7aa760fa.png)
> 
> and type below in terminal
> npx swagger-typescript-api --templates ./templates --axios

Oh yeah I didn't think about using custom templates for this. I used them for something else but forgot it can also be applied here. Good catch!

Unfortunately this means you will have to keep this template updated as `swagger-typescript-api` gets updated just so that you get all the latest code. 

But at least there is a way to expose this AxiosInstance after all.

**Comment by bezvrednyy** [comment]
Is it possible to redefine the type of the returned value?
I want to use [Either monad.] (https://github.com/JSMonk/sweet-monads/tree/master/either) To do this, in `axios.interceptors.response`, I wrap everything in Either object. But I need to report this to typescript somehow.

**Comment by himanshs** [comment]
> I just successed using template.
> 
> make directory "templates" and make "http-client.eta" file in "templates" directory and copy https://github.com/acacode/swagger-typescript-api/blob/next/templates/base/http-clients/axios-http-client.eta and paste into "http-client.eta" and change private instance: AxiosInstance; => instance: AxiosInstance;
> 
> ![image](https://user-images.githubusercontent.com/9765614/115210924-080a4d00-a13a-11eb-9d0e-124f7aa760fa.png)
> 
> and type below in terminal npx swagger-typescript-api --templates ./templates --axios

Can we somehow inject the interceptor in the client kit itself as it is required for all api call? It  not good idea to write the same interceptor code in all apis.
