### ISSUE TITLE
Add summary as JSDoc comment

### ISSUE THREAD

**Issue by bnjmnt4n** [acacode/swagger-typescript-api#235]
Here's an example of a generated JSDoc for an API request method:

```
    /**
     * No description
     *
     * @tags Tag
     * @name Name
     * @summary Get information about data.
     * @request GET:/path/to/route
     * @secure
     */
```

It would be great if the summary could be added as the main JSDoc description if the operation description does not exist.

**Comment by js2me** [comment]
I don't think that it is so important for usage, but you can customize that with `--templates` option

**Comment by bnjmnt4n** [comment]
Sure, it's not exactly very important, but I thought it would be more convenient than having to redeclare the whole template.

**Comment by js2me** [comment]
@bnjmnt4n Also you can use `onCreateRoute` hook to achieve this
