### ISSUE TITLE
All types is optional

### ISSUE THREAD

**Issue by TommySorensen** [acacode/swagger-typescript-api#269]
Running the default template like this generates all interfaces as `optional` which is kind of weird. 
```
npx swagger-typescript-api -p https://blablaurl -o ./models/ -n index.ts --no-client --extract-request-params --extract-request-body
```
Schema from swagger json file to the response of a normal json endpoint:
![image](https://user-images.githubusercontent.com/4134473/122409412-66f61200-cf83-11eb-8e3e-af6f1b227e99.png)

Generated model file:
```ts
export interface BasketHeader {
  nameId?: string | null;
  basketName?: string;

  /** @format int32 */
  linesCount?: number;
  basketPosInfo?: string | null;
  lines?: FavoriteProduct[];
}
```

Is it me or is this a bug?

**Comment by js2me** [comment]
Hello @TommySorensen !  
You need to add `required` property   
https://swagger.io/docs/specification/data-models/data-types/   

```
"required": ["basketName"]
```

**Comment by TommySorensen** [comment]
> Hello @TommySorensen !
> You need to add `required` property
> https://swagger.io/docs/specification/data-models/data-types/
> 
> ```
> "required": ["basketName"]
> ```

Thx will try with that.

**Comment by jeking3** [comment]
@TommySorensen if that worked, remember to update or close this issue.  Thanks!
