### ISSUE TITLE
Tiny question about your hooks

### ISSUE THREAD

**Issue by schillerenrico** [acacode/swagger-typescript-api#271]
Hello!
I justed wanted to use your **onFormatTypeName** hook but I cant find an instruction how to use it.
I want to generate the output via npx and it would be great if I could add to the hook via cli or something.
How do you guys use the hooks?
An example would be awsome!

Thank you very much in advance!

**Comment by sinclairnick** [comment]
I don't think this is possible via CLI, however I've used the JS version of that exact hook. Taking the `typeName` as input, you can return a string that would replace this. For example

```ts
(typeName) => `_${typeName}`
```
would prefix an underscore to all typenames

**Comment by schillerenrico** [comment]
@sinclairnick Thanks!
I wrote a little node js file wich uses the hook the same way as you suggested. And its working great via cli by

`    "syncinterfaces:swagger-ts-api": "node importSwagger.node.js"`
