### ISSUE TITLE
Clashing of "query" name in the produced code

### ISSUE THREAD

**Issue by unclechu** [acacode/swagger-typescript-api#28]
![Screenshot from 2020-03-12 21-04-17](https://user-images.githubusercontent.com/799353/76558679-6a5c3d00-64a6-11ea-9392-1e6e4b92cc71.png)
Used version: `1.5.0`

**Comment by js2me** [comment]
Hello! Thanks for your issue, I'll start working on it.  
Also type of the query params is wrong too ?  
![image](https://user-images.githubusercontent.com/16340911/76594117-4120c880-6509-11ea-966f-81f9e3bc46b2.png)

**Comment by js2me** [comment]
@unclechu can you attach part of your swagger schema if it is possible ?

**Comment by unclechu** [comment]
@js2me 
> Also type of the query params is wrong too ?

No, the type is completely fine, it's exactly what I wanted it to be. Kind-of stringy enum of a single value.

**Comment by unclechu** [comment]
@js2me I'll provide a Swagger schema soon, hopefully today. It comes from that I have `{query}` captured from the URL path (*pathname*).

**Comment by js2me** [comment]
@unclechu got it :)  
![image](https://user-images.githubusercontent.com/16340911/76677199-91b52600-65dc-11ea-8a76-aa4cf9914507.png)

I will fix it today

**Comment by js2me** [comment]
Fixed in `1.6.0` version.
