### ISSUE TITLE
typescript-axios cancellation support

### ISSUE THREAD

**Issue by VincentVanclef** [acacode/swagger-typescript-api#288]
Hi there,

How does cancellation work with typescript-axios? I found this:

https://github.com/acacode/swagger-typescript-api/issues/96

But this seems either outdated, or not working for the typescript-axios version.

As it requires a CancelToken, and Api does not expose a abortRequest either.

What is the way to handle cancellations?

Thanks!

**Comment by VincentVanclef** [comment]
Figured it out, for anyone else who needs it, just send the canceltoken with the params object:

**Comment by NightmanCZ90** [comment]
Hello, could you please ellaborate? I want to use this library for our application. But I cannot seem to cancel a request. Could you show a visual example also? Thank you in advance.
