### ISSUE TITLE
Type errors when compiling with the --axios option

### ISSUE THREAD

**Issue by Isaac-Leonard** [acacode/swagger-typescript-api#301]
I get these errors when running tsc after generating the api with the axios option.
The normal fetch option works fine however I am targeting node and node-fetch doesn't want to work with it.
The compilation errors I get are:
src/api/data-portal.ts:471:7 - error TS2532: Object is possibly 'undefined'.

471       requestParams.headers.common = { Accept: "*/*" };
          ~~~~~~~~~~~~~~~~~~~~~

src/api/data-portal.ts:471:7 - error TS2322: Type '{ Accept: string; }' is not assignable to type 's
tring'.

471       requestParams.headers.common = { Accept: "*/*" };
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/api/data-portal.ts:472:7 - error TS2532: Object is possibly 'undefined'.

472       requestParams.headers.post = {};
          ~~~~~~~~~~~~~~~~~~~~~

src/api/data-portal.ts:472:7 - error TS2322: Type '{}' is not assignable to type 'string'.

472       requestParams.headers.post = {};
          ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/api/data-portal.ts:473:7 - error TS2532: Object is possibly 'undefined'.

473       requestParams.headers.put = {};
          ~~~~~~~~~~~~~~~~~~~~~

src/api/data-portal.ts:473:7 - error TS2322: Type '{}' is not assignable to type 'string'.

473       requestParams.headers.put = {};
          ~~~~~~~~~~~~~~~~~~~~~~~~~

Found 6 errors.
I generate the api successfully with the command:
npx swagger-typescript-api --path src/un-data-portal.json -o ./src/api/ -n data-portal.ts --axios
And then run:
npx tsc
If there is no easy fix for this does anyone know how to get node-fetch working with the default version instead?
In case it matters I'm using the latest versions of axios and swagger-typescript-api and using node v16.8.0 with typescript Version 4.4.3 .

**Comment by Isaac-Leonard** [comment]
Heres the relevant lines in the outputted file starting from line 70:
    if (type === ContentType.FormData && body && body !== null && typeof body === "object") {
      requestParams.headers.common = { Accept: "*/*" };
      requestParams.headers.post = {};
      requestParams.headers.put = {};

      body = this.createFormData(body as Record<string, unknown>);
    }

**Comment by kompasbank-niels** [comment]
I have the same issue and worked around it by adding // @ts-ignore before those 3 lines.

**Comment by Isaac-Leonard** [comment]
I've done that for now but its not really a sustainable option if I end up sticking with my current project.
I could look into making a pull request with a proper fix but atm I'm not sure what is meant to actually be happening there.

**Comment by grandsilence** [comment]
Use the [swagger-typescript-api-nextgen](https://github.com/grandsilence/swagger-typescript-api-nextgen) fork, it solves this problem. The package is present in the [npm](https://www.npmjs.com/package/swagger-typescript-api-nextgen).
