### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by js2me** [acacode/swagger-typescript-api#31]
NodeJS is not support `fetch`.   
Needs to find a better way how to support nodejs usage generated Api module

**Comment by JennieJi** [comment]
Hi @js2me , I think it will also be a good idea to let user pass their own fetch function

**Comment by jfsiii** [comment]
@JennieJi @js2me agreed. This way they can supply `node-fetch` or any `fetch`-compatible function

**Comment by js2me** [comment]
@jfsiii @JennieJi as simple solution for support NodeJS and own fetch function - it's customizing mustache templates

**Comment by JennieJi** [comment]
Understood, didn't see this option, kind of unobvious

**Comment by js2me** [comment]
@JennieJi Yes, you are right, needs to update README.md

**Comment by ryzhov** [comment]
+1

**Comment by js2me** [comment]
I think support NodeJS solution is not a good idea because it will not suitable for everyone.  
And because of this, better that you will use custom ETA templates option `--templates` and make your own solution for your project on NodeJS.

**Comment by OnkelTem** [comment]
> I think support NodeJS solution is not a good idea because it will not suitable for everyone.

You could provide a default solution for NodeJS users instead of just banning them.

**Comment by jfsiii** [comment]
> NodeJS is not support fetch

This has changed since the ticket was created. Global `fetch` is [enabled by default in node 18](https://nodejs.org/en/blog/announcements/v18-release-announce/#fetch-experimental). 

I'm not sure how this changes things for this project or this ticket, but it is an important development.
