### ISSUE TITLE
route-name.eta customize routeParts length

### ISSUE THREAD

**Issue by alex-shatalov** [acacode/swagger-typescript-api#355]
Hi, i have a problem that my api path "/v1/job/{job_result_id}" generates into "getV1".
If am right, the reason why it gets "getV1" name is 
`routeParts.length > 3`
in route-name.eta

is it possible to configure number 3? If i change condition to
`routeParts.length >= 3` I get exactly what i need

I know that i can do whatever i want in hooks config, but all I need is just change condition

**Comment by js2me** [comment]
This project has ability to customize everything as it possible with using `.eta` templates .  
You can use option `--templates` and set directory with your custom templates.   
Also as you said you can use hooks which are also able to do your customization.   

With my experience with this project I understand one thing - it is not possible to craete silver bullet which will be able to solve all dev problems with using swagger schemas and so on. But I added ability to customize almost everything as you want.
