### ISSUE TITLE
What is difference with OpenAPI Generator or Swagger Codegen?

### ISSUE THREAD

**Issue by wirekang** [acacode/swagger-typescript-api#364]
What are the advantages of swagger-typescript-api?

**Comment by NikitaIT** [comment]
To be honest, there is not a single generator for the swagger that covers the specification and is suitable for both generating ts and yaml. I tried them all and only this one worked with my config.

This generator has slightly more specification coverage than others and the types it creates are easy to use. But it is not supported. You may need to try all the options to find the one that works for your specification.
