### ISSUE TITLE
get请求中同时包含path参数和query参数报错

### ISSUE THREAD

**Issue by amberlwan** [acacode/swagger-typescript-api#368]
Error: Swagger schema parse error!

| listUsingGet2({ { groupId, ...query } }: { { groupId, ...query }: ListUsingGet2Params },params: RequestConfig = {}) {
     |                 ^
  17 |     return request<any>({
  18 |         url: `/arch/group-members/list/${groupId}`,
  19 |         method: 'GET',

 TypeError: Cannot read properties of null (reading 'map')
    at D:\projects\jp-axios\node_modules\.pnpm\registry.npmmirror.com+swagger-typescript-api@9.3.1\node_modules\swagger-typescript-api\src\index.js:262:17

**Comment by js2me** [comment]
Hello @amberlwan can you shared part of your swagger schema which crashes this tool?

**Comment by amberlwan** [comment]
这个通过改模版后就解决了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sergey S. Volkov ***@***.***&gt;
发送时间: 2022年8月17日 14:51
收件人: acacode/swagger-typescript-api ***@***.***&gt;
抄送: amberlwang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [acacode/swagger-typescript-api] get请求中同时包含path参数和query参数报错 (Issue #368)

**Comment by js2me** [comment]
@amberlwan I can fix this problem in project, can you share issued part of swagger schema?
