### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by wirekang** [acacode/swagger-typescript-api#374]
Does this project supports below example?

Example:
```
/foo/asdf
/foo/bar/qwer
/foo/bar/baz/zxcv
```

Expected output:
```js
api.foo.asdf()
api.foo.bar.qwer()
api.foo.bar.baz.zxcv()
```

**Comment by azymnis** [comment]
Hi there, any chance you could take another look at this issue? We have a fairly complex api that involves nested resources. It is a bit inconvenient to have to push all endpoints at the top level resource

**Comment by wirekang** [comment]
I'm sorry that there is no workaround for this issue as far as I know. I can't remember why I closed this issue as not planned either.

**Comment by azymnis** [comment]
@wirekang btw if you could point me and and @0x2539 to the relevant places, we would be happy to help with a PR

**Comment by wirekang** [comment]
OpenApi itself doesn't have a concept of nested paths, so there's not much the generated client can do.
How about generated multiple client based on path?

| some option | path | generated class|
| ---- | --- | --- |
| 0 (default) | /users | Api |
| 0  | /pets | Api |
| 1 (split api class based on first part of path) | /users | UserApi |
| 1 | /pets | PetApi |

**Comment by azymnis** [comment]
I like that option

**Comment by arashi-dev** [comment]
Did anyone find any solution?
