### ISSUE TITLE
How to override a template?

### ISSUE THREAD

**Issue by OnkelTem** [acacode/swagger-typescript-api#375]
I read the docs but still have no clue what I do to edit for example interfaces generation.
I copied `templates/default/*` from the repo into my project `templates/*`
But in there I don't see any interface generation. Because it happens in the `base/*`. But I didn't copy `base/*`. And if I do, it uses some defaults via `@base`... which is not the `base/*` that I copied, isn't it? So how it is assumed to override things from the `@base` space?

**Comment by marko-hologram** [comment]
As docs mention, you just copy individual files, not the whole folder structure. https://github.com/acacode/swagger-typescript-api#--templates

So I can give one example how I did this, but I only updated api client and route names, not others.
At the root of my project, this is the folder structure for templates:

![image](https://user-images.githubusercontent.com/22904204/182560238-2caebc71-0059-4d3f-8b2c-9f5370cb01f1.png)

And I've just added template path to the command I run `npx swagger-typescript-api --templates ./swaggerGenerateTemplates`  I've omitted other arguments because they are not important here.

**Comment by OnkelTem** [comment]
Thank you, let me try it!

**Comment by OnkelTem** [comment]
@marko-hologram Ok, I've tried that it, but maybe I do something wrong, because it shows me the following error:

```
...
✨   try to read templates from directory "/projects/project/templates"
⚠️    api template not found in /projects/project/templates/api.eta
```

My templates directory looks like:

![image](https://user-images.githubusercontent.com/114060/183296715-3e422d9d-fb54-4f1a-80e8-66b52da3375c.png)

**Comment by OnkelTem** [comment]
This is how I invoke the tool:

```
"swagger-typescript-api --templates templates --clean-output --modular --module-name-index 1 -p ./src/api/vms-swagger.json -o ./src/api/__gen__",
```

So I think that I should pick files from the templates/modular folder. They are:

```
api.eta
procedure-call.eta
route-types.eta
```

but I need to override data-contracts, and I don't see any data contracts inside these files.

**Comment by marko-hologram** [comment]
@OnkelTem Oh, are you trying to run `swagger-typescript-api` that is installed locally inside your project or are you using `npx` to run this module? Judging by your comment, it seems like you have an npm script that runs this locally installed version.

As you can see in my example, I specifically use `npx swagger-typescript-api --templates ./swaggerGenerateTemplates`. I remember I had some issues running locally installed version so I just default to using npx to pull latest version and run that immediately. That might help you.

Btw, if you want to be sure you are always running the same version, you can still define it like `npx swagger-typescript-api@9.0.0` and that will for example run v9.0.0, even though a newer version might exist.

**Comment by OnkelTem** [comment]
@marko-hologram I'm running the latest version which is `9.3.1`. Not sure tho, if there's a difference between local or global installation. It's listed in our `devDependencies` list.

@js2me, Sergey, do you have any idea why templates don't work?

**Comment by marko-hologram** [comment]
@OnkelTem that's why I'm advising you to try to run it with `npx` without it being locally installed in the project. So it shouldn't be listed in dependencies/devDependencies and not installed in node_modules.

I know I ran into some issue when I tried to run it long time ago as a local project dependency, something just didn't work. I defaulted to using `npx` directly without the dependency being installed locally inside the project and have been using it like that ever since.

**Comment by OnkelTem** [comment]
@marko-hologram Ok, I removed it from the local packages ran it with `npx`. Honestly, there was no difference, but I realized that it's probably using the template but for some reason **doesn't say anything about it!**

So I have only one file in the `./templates/` dir which is: `data-contracts.eta` but here is my output:

```
$ npm run api-generate

> vms-canvas@1.0.2 api-generate
> npx swagger-typescript-api --templates=templates --clean-output --modular --module-name-index 1 -p ./src/api/vms-swagger.json -o ./src/api/__gen__

✨   try to get swagger by path "/projects/project/src/api/vms-swagger.json"
✨   try to read templates from directory "/projects/project/templates"
⚠️    api template not found in /projects/project/templates/api.eta 
⚠️    Code generator will use the default template
⚠️    route types template not found in /projects/project/templates/route-types.eta 
⚠️    Code generator will use the default template
☄️    start generating your typescript api
✅   typescript api file data-contracts.ts created in /projects/project/src/api/__gen__
✅   typescript api file http-client.ts created in /projects/project/src/api/__gen__
✅   typescript api file V1.ts created in /projects/project/src/api/__gen__

```

**Comment by marko-hologram** [comment]
@OnkelTem Yeah that output seems fine. Whenever I run it, it says "try to read templates from directory ..." and then "api template not found in ...", but it works.

I just ran it locally in my project and the output is the same. I think it just says that it cannot find a specific template in your template folder and then it probably falls back to default template. So I'm guessing it all works fine for you now?

**Comment by OnkelTem** [comment]
Yep, @marko-hologram. Thanks for being persistent :) Now we know that the problem was actually in bad console feedback.

**Comment by vinoddotcom** [comment]
Run 

``` templates: "npx swagger-typescript-api generate-templates -o ./my-templates```

Overrides the file insdie my-templates.

Modify
```
import { generateApi } from "swagger-typescript-api";

await generateApi({
  input: "./swagger.json",
  output: "./src/api",
  templates: "./my-templates",
  /* …other options… */
});

```
