### ISSUE TITLE
NPM release for 'next' branch

### ISSUE THREAD

**Issue by inomn** [acacode/swagger-typescript-api#378]
Hi! Are there any plans to merge `next` to `master` \ release `next` branch to NPM?

Also is https://github.com/grandsilence/swagger-typescript-api-nextgen an unofficial fork?

**Comment by js2me** [comment]
Hello @inomn , yes https://github.com/grandsilence/swagger-typescript-api-nextgen is unofficial fork,   
My plans to merge next branch into master about couple days.   
Currently I'm merging all other possible live pull requests, and adding new custom features like --extract-response-body
