### ISSUE TITLE
api calls names

### ISSUE THREAD

**Issue by VitaliKhileuski** [acacode/swagger-typescript-api#380]
How can i customize name generating of api calls? For this moment i see that name generate from route parts and word Create that is not comfortable for me
![image](https://user-images.githubusercontent.com/57916019/184615915-8d2dffb9-be8f-4bd3-a768-56175a21f162.png)

**Comment by TimAlaerts** [comment]
@VitaliKhileuski in case you are still wondering you can specify the name in swagger via the "operationId" property and the generator will use that name instead

**Comment by js2me** [comment]
Hello @VitaliKhileuski  !  
You can use hooks api \ templates (route-name) for customizing name generating of api calls  

In my case I use hooks api   
![image](https://user-images.githubusercontent.com/16340911/185710227-2fc4d83d-60eb-4030-999f-cb9a50fee836.png)

Where `generateOperationId` is   
```

const ACTION_METHODS = ["post", "put", "patch"]

const generateOperationId = (routeInfo) => {
  const {
    method,
    route,
    moduleName,
    pathArgs,
  } = routeInfo;

  const usageRoutePart = _.split(route, moduleName)[1] || _.split(route, _.kebabCase(moduleName))[1]
  const parts = _.split(route, "/");
  const lastPart = _.last(parts);

  const firstPathArg = pathArgs[0]

  if (!usageRoutePart) {
    return _.camelCase(`${method}_${moduleName}`)
  }

  return _.camelCase(_.compact([
    ACTION_METHODS.includes(method) ? "" : method,
    lastPart,
    ...(firstPathArg && firstPathArg.name !== lastPart ? [
      'by',
      firstPathArg.name
    ] : []),
  ]).join('_'))
};

```

**Comment by js2me** [comment]
Otherwise you are able to change operation id with using templates   
https://github.com/acacode/swagger-typescript-api/blob/master/templates/base/route-name.eta

**Comment by VitaliKhileuski** [comment]
Thanks

**Comment by VitaliKhileuski** [comment]
@js2me  Thanks, I used operation id as names

**Comment by Leningram** [comment]
Where should I put the config with hooks? In what file and what folder? I just have swagger.json in my root folder of react app and then just run npx swagger-typescript-api ...etc
