### ISSUE TITLE
[v10.0.1]: Unreachable code detected in createFormData method (typescript axios)

### ISSUE THREAD

**Issue by ApacheEx** [acacode/swagger-typescript-api#391]
Hi,

it looks like there is unreachable code detected in createFormData method (typescript axios):

![image](https://user-images.githubusercontent.com/1918108/185388446-04dc6562-f1b9-4d76-8b25-7ba0b518eb81.png)

**Comment by vnylbscr** [comment]
Same problem on my project.

**Comment by juanmait** [comment]
I'm also seeing the same issue. I have a sonar project that considers this as a bug.

**Comment by js2me** [comment]
Problem has been fixed in releases 11.*   
FYI anytime you can customize codegen templates as you want,
