### ISSUE TITLE
Question/Feature Request: Generating array types to use generic syntax

### ISSUE THREAD

**Issue by SarahFowler73** [acacode/swagger-typescript-api#414]
I have read through docs and issues, and haven't been able to find out if there's a way to do this. 

### Current behavior
The tool currently generates array types in `data-contracts.ts` using the following syntax:
```
export interface ModuleListResponse {
  modules: {
    description: string;
    title: string;
    version: number;
  }[];
}
```

### Desired behavior
For the purposes of readability and consistency in our codebase, I'd like to generate the type using the generic syntax:
```
export interface ModuleListResponse {
  modules: Array<{
    description: string;
    title: string;
    version: number;
  }>;
}
```

Is there a way to accomplish this in the current implementation?

**Comment by js2me** [comment]
Added support of this feature in 11.0.0   
`--another-array-type` option
