### ISSUE TITLE
mime types with charset parameter is not handled

### ISSUE THREAD

**Issue by JochenDiekenbrock** [acacode/swagger-typescript-api#440]
If the swagger document contains a mime type with a charset parameter, for example
```
      consumes:
        - application/json;charset=UTF-8
```
the generated api does set not a type definition,
```
type: ContentType.Json,
```
is missing.

**Comment by js2me** [comment]
@JochenDiekenbrock thank you, added in 11.1.3

**Comment by JochenDiekenbrock** [comment]
> @JochenDiekenbrock thank you, added in 11.1.3

Thank you too, Sergey!
