### ISSUE TITLE
Support for encoding route params

### ISSUE THREAD

**Issue by Liwoj** [acacode/swagger-typescript-api#446]
In case this was discussed before, pleas point me into a right direction - I was not able to find anything.

In case of "in path" params, the generated client code just uses simple string interpolation to create a path. For example: `path: ``/Overrides/Reasons/${ratingSegmentIdent}\`` `

This means that any param is included in the path by calling `ToString()` which is not always the best approach. First it could be great if there was a way to automatically use `encodeURIComponent()` to encode the param. Second in case of `Date` param, the `ToString()` is definitelly not what you want to have in the path

Maybe provide some additional hook to allow us to encode the params ?

Thanks!

**Comment by js2me** [comment]
Hi @Liwoj , that's good point for enhancement swagger-typescript-api!   
I think is better way to solve your problem - create specific pregenerate hook linked with creating route path

**Comment by js2me** [comment]
Hi @Liwoj your problem should be fixed in 12.0.0   
Please use the `onInsertPathParam` hook, example here   
https://github.com/acacode/swagger-typescript-api/blob/master/tests/spec/on-insert-path-param/test.js

**Comment by Liwoj** [comment]
Nice! I'll try it right away! Thank you very much for this great tool!

**Comment by Liwoj** [comment]
Sorry to take too long to actually try the changes. I'm looking at the code and sure, the new `onInsertPathParam` hook is perfect for auto-encoding the path parameters. But I'm not sure if the other mentioned use-case (changing how param value is insserted inot a path based on the **type** of the param - `Date` in me case) can be done without any type information from the schema... 

??

**Comment by fungiboletus** [comment]
Shouldn't `encodeURIComponent` be the default, as it may be a good idea to prevent url injections.

**Comment by ramondeklein** [comment]
@fungiboletus That should be the default. There is absolutely no use-case for not doing this...
