### ISSUE TITLE
How to use extraTemplates?

### ISSUE THREAD

**Issue by christo8989** [acacode/swagger-typescript-api#448]
I'm trying to add extra templates but I can't seem to get it to work.

```
await generateApi({
  ...,
  extraTemplates: [
    path.resolve(process.cwd(), './src/generated/templates/extra/template.eta')
  ],
})
```

```
const foo = 'extra template';
```

Error: ❌ https://host.com/service/v2/api-docs [FAILED CODEGEN]

**Comment by js2me** [comment]
Hi @christo8989 , I forgot add more documentation about this field.   
First of all, extraTemplates has struct like  
```
{ name: string, path: string }[];
```   

it generates one ts\js file per one extra template   

See more examples here: https://github.com/acacode/swagger-typescript-api/tree/next/tests/spec/extra-templates

**Comment by christo8989** [comment]
Thank you!
