### ISSUE TITLE
How to configure route names

### ISSUE THREAD

**Issue by Leningram** [acacode/swagger-typescript-api#449]
Now I get names like getTradingInstrumentBrokersBrokerIdentTradeInstrumentsTiIdentGet 
It contains the name, the route. the method and everything else.
How can I change the names? Where should I use the file with hooks and where can I find the docs for its values?
If I make .js file with hooks and run it with node, changing url to my .json I get an error: [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined

**Comment by Leningram** [comment]
I used your file in parse-swagger.js, run node parse-swagger.js and got the error:
 const required = _.uniq([...(parentSchema.required || []), ...(childSchema.required || [])]);
                                                       ^

TypeError: (parentSchema.required || []) is not iterable

**Comment by js2me** [comment]
@Leningram can you share part of your swagger schema with "required" property ?

**Comment by Leningram** [comment]
`	"/currencies": {
			"get": {
				"tags": ["currency"],
				"summary": "Get Currencies",
				"description": "<h1>Role: currencies.list</h1>",
				"operationId": "get_currencies_currencies_get",
				"parameters": [
					{
						"required": false,
						"schema": {
							"title": "Page",
							"minimum": 1.0,
							"type": "integer",
							"default": 1
						},
						"name": "page",
						"in": "query"
					},
					{
						"required": false,
						"schema": {
							"title": "Size",
							"type": "integer",
							"default": 1
						},
						"name": "size",
						"in": "query"
					}
				],
				"responses": {
					"200": {
						"description": "Successful Response",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ResponsePaginationApi_list_app.models.currency.currency.Currency__"
								}
							}
						}
					},
					"422": {
						"description": "Validation Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/HTTPValidationError"
								}
							}
						}
					}
				},
				"security": [
					{
						"OAuth2PasswordBearer": []
					}
				]
			},`

**Comment by Leningram** [comment]
It parse json perfect but if I use npx command. And it's ok but I would like to change names.

**Comment by Leningram** [comment]
And now it runs with no error but result api.ts file contains some standart methods and interfaces not from my swagger

**Comment by trankhacvy** [comment]
@Leningram how to you fix your issue? I got same error.

**Comment by Leningram** [comment]
`const { generateApi } = require('swagger-typescript-api');
const path = require('path');
const ACTION_METHODS = ['post', 'put', 'patch'];
const _ = require('lodash');
const generateOperationId = (routeInfo) => {
  const {
    method,
    route,
    moduleName,
    pathArgs,
  } = routeInfo;

  const usageRoutePart = _.split(route, moduleName)[1] || _.split(route, _.kebabCase(moduleName))[1]
  const parts = _.split(route, "/");
  const lastPart = _.last(parts);

  const firstPathArg = pathArgs[0]

  if (!usageRoutePart) {
    return _.camelCase(`${method}_${moduleName}`)
  }

  return _.camelCase(_.compact([
    ACTION_METHODS.includes(method) ? "" : method,
    lastPart,
    ...(firstPathArg && firstPathArg.name !== lastPart ? [
      'by',
      firstPathArg.name
    ] : []),
  ]).join('_'))
};
generateApi({
	name: 'apiServices.ts',
	output: path.resolve(process.cwd(), './src/infrastructure/httpLayer'),
	url: 'http://....../openapi.json',
	httpClientType: 'axios',
	hooks: {
    onFormatRouteName: (routeInfo, templateRouteName) => {
			// if (!routeInfo.operationId) {
			return generateOperationId(routeInfo); // this is my custom generation route name
			// }

			return templateRouteName; // this is generated route name from swagger-typescript-api
		},
		onPrepareConfig: (configuration) => {
			// configuration.routes.combined = configuration.routes.combined.filter(route => route.moduleName !== "ws")
		},
	},
});`

**Comment by Leningram** [comment]
> @Leningram how to you fix your issue? I got same error.

That is my .js config file
