### ISSUE TITLE
How to handle circular references caused by polymorphism

### ISSUE THREAD

**Issue by evtk** [acacode/swagger-typescript-api#456]
Hello, I'm running into issues with circular references caused by a setup that contains polymorphism in the classes. I'm wondering how to handle these cases.

Take the below schema as an example. `BlockDTO` has `type` property indicating the type of `BlockDTO`. It can be a `CsvBlockDTO` or a `FileBlockDTO`. 

**Schema**
```
schemas:
    BlockDTO:
      required:
      - title
      type: object
      properties:
        title:
          type: string
          nullable: false
      discriminator:
        propertyName: type
        mapping:
          csv: '#/components/schemas/CsvBlockDTO'
          file: '#/components/schemas/FileBlockDTO'
      oneOf:
      - $ref: '#/components/schemas/CsvBlockDTO'
      - $ref: '#/components/schemas/FileBlockDTO'
    CsvBlockDTO:
      allOf:
      - $ref: '#/components/schemas/BlockDTO'
      - required:
        - text
        - type
        type: object
        properties:
          type:
            type: string
            default: csv
            enum:
            - csv
          text:
            type: string
            nullable: false
    FileBlockDTO:
      allOf:
      - $ref: '#/components/schemas/BlockDTO'
      - required:
        - fileId
        - type
        type: object
        properties:
          type:
            type: string
            default: file
            enum:
            - file
          fileId:
            type: string
            nullable: false
```
            
This schema is generated as below, but clearly results in typescript errors due to `BlockDTO` referencing `CsvBlockDTO` while `CsvBlockDTO` is also referencing `BlockDTO`.

```
export type BlockDTO = (CsvBlockDTO | FileBlockDTO) & {
  title: string;
};

export type CsvBlockDTO = BlockDTO & {
  /** @default "csv" */
  type: "csv";
  text: string;
};

export type FileBlockDTO = BlockDTO & {
  /** @default "file" */
  type: "file";
  fileId: string;
};
```

I think the only way to solve this is to create some sort of abstract class, but it isn't an option to configure on this generator. Nor did I find it to be an option on any of the other openapi->typescript generators I found so far.

```
export interface AbstractBlockDTO {
  type: "csv" | "file";
  title: string;
}

export type BlockDTO = CsvBlockDTO | FileBlockDTO;

export type CsvBlockDTO = AbstractBlockDTO & {
  type: "csv";
  text: string;
};

export type FileBlockDTO = AbstractBlockDTO & {
  type: "file";
  fileId: string;
};

Any thoughts / suggestions?

**Comment by js2me** [comment]
Hi @evtk !   
Thanks for this interesting problem, that is more enhancement than bug, currently swagger-typescript-api is not supporting descriminator (as I know ahah but I'm not sure)   
But based on this problem I think I'll try to add support of this property and will fix your problem!

**Comment by js2me** [comment]
@evtk I think the best solution of this is   
![image](https://user-images.githubusercontent.com/16340911/201776041-eb7d3a2c-883b-4614-b564-82a3fd085e54.png)

Because if we based on your schema with duplicates of usage types inside BlockDTO   
![image](https://user-images.githubusercontent.com/16340911/201776160-fedf5fdb-018d-42e7-b4e5-7c0d1aa3090c.png)


I have another example without "oneOf"   

```json
  "Pet": {
      "type": "object",
      "required": [
        "pet_type"
      ],
      "properties": {
        "pet_type": {
          "type": "string"
        }
      },
      "discriminator": {
        "propertyName": "pet_type",
        "mapping": {
          "cachorro": "#/components/schemas/Dog",
          "cat": "#/components/schemas/Cat"
        }
      }
    },
    "Cat": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Pet"
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "Dog": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Pet"
        },
        {
          "type": "object",
          "properties": {
            "bark": {
              "type": "string"
            }
          }
        }
      ]
    },
```

![image](https://user-images.githubusercontent.com/16340911/201776264-eb43bea0-8c0a-44f7-affe-24b84a8461ea.png)


What do you think ?

**Comment by js2me** [comment]
https://github.com/acacode/swagger-typescript-api/tree/next/tests/spec/discriminator

**Comment by evtk** [comment]
@js2me first of all:  this is really awesome, never seen this proactive approach on topics like this before. Kuddos!

Your proposal reflects my line of thoughts and I will solve the issues existing with the circular ref. I'm trying to understand though why you have chosen to generate the `BlockDTO` as:

```
export type BlockDTO =
  | AbstractBlockDto
  | (CsvBlockDTO | FileBlockDTO)
  | (
      | ({
          type: "csv";
        } & CsvBlockDTO)
      | ({
          type: "file";
        } & FileBlockDTO)
    );
```

instead of:

```
export type BlockDTO = (CsvBlockDTO | FileBlockDTO)
```

Only the latter will give me the type errors I would expect:

![Scherm­afbeelding 2022-11-15 om 09 28 04](https://user-images.githubusercontent.com/1754392/201871643-646cd844-d309-4114-8a73-fc3e2dc86a4b.png)
![Scherm­afbeelding 2022-11-15 om 09 28 35](https://user-images.githubusercontent.com/1754392/201871647-bffb8fc7-a73f-4c0e-880f-69f88b12cfa7.png)

**Comment by js2me** [comment]
@evtk yeah, good point.   
But what can I do with schemas like?   
```

    "Pet": {
      "type": "object",
      "required": [
        "pet_type"
      ],
      "properties": {
        "pet_type": {
          "type": "string"
        }
      },
      "discriminator": {
        "propertyName": "pet_type",
        "mapping": {
          "cachorro": "#/components/schemas/Dog",
          "cat": "#/components/schemas/Cat"
        }
      }
    },
    "Cat": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Pet"
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "Dog": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Pet"
        },
        {
          "type": "object",
          "properties": {
            "bark": {
              "type": "string"
            }
          }
        }
      ]
    },
```

because currently it generates typescript code like   

```


interface AbstractPet {
    pet_type: string;
}

export type Pet =
  | AbstractPet
  | (
      | ({
          pet_type: "cachorro";
        } & Dog)
      | ({
          pet_type: "cat";
        } & Cat)
    );

export type Cat = AbstractPet & {
  name?: string;
};

export type Dog = AbstractPet & {
  bark?: string;
};
```

Which is technically correct

**Comment by js2me** [comment]
Main problem of this interesting schema is that `Cat` and `Dog` dont have "constant" identifiers like `pet_type: "cachorro"` or `pet_type: "cat"` inside their own swagger schema  
```json
 "Dog": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Pet"
        },
        {
          "type": "object",
          "properties": {
            "bark": {
              "type": "string"
            }
          }
        }
      ]
    }
```

**Comment by evtk** [comment]
Yes, well I'm then wondering if that swagger schema for Dog is valid. I think that I would expect the following:  

when Pet has this mapping inside the descriminator

```
"discriminator": {
        "propertyName": "pet_type",
        "mapping": {
          "cachorro": "#/components/schemas/Dog",
          "cat": "#/components/schemas/Cat"
        }
      }
```

then `Dog` should always have that `pet_type` defined in its own schema as a required property.

```

 "Dog": {
    "allOf": [
        {
            "$ref": "#/components/schemas/Pet"
        },
        {
            "required": [
                "pet_type"
            ],
            "type": "object",
            "properties": {
                "pet_type": {
                    "type": "string",
                    "default": "cachorro",
                    "enum": [
                        "cachorro"
                    ]
                }
            }
        }
    ]
}

But I'm not an expert on the validness of those schemas :)

**Comment by evtk** [comment]
@js2me a side note I just discovered while working with the new `--extract-enums` property you have added. We have an issue when using the extracted enums for this polymorphic setup.

![Scherm­afbeelding 2022-11-15 om 16 43 59](https://user-images.githubusercontent.com/1754392/201962826-4f0b5fa0-9329-4145-9449-cea4dcd590c1.png)

> The intersection was reduced to 'never' because property 'type' has conflicting types in some constituents.

So we are assigning `BlockType` and `CsvBlockType` to the same `type` property 🤔, which typescript doesn't like. That would not be an issue when we are not abstracting the enums and using the union types.

**Comment by dirkgroenen** [comment]
> But I'm not an expert on the validity of those schemas :). I'll contact my co-workers to bring this to their attention and to see what solutions/thoughts they can come up with.

Co-worker calling for duty! 😉 Disclaimer, I'm just as much an expert as @evtk is, so all I can do here is share my line of thoughts. 

To me it feels like we should focus on the `discriminator` and make some 'magic' around it. The screenshot Erik shared in his last comment to me feels like the correct output. As an exercise for myself I tried to breakdown the schema YML into Typescript code and left notes all over the place:

```yml
BlockDTO:
  required:
  - title
  type: object
  properties:
    title:
      type: string
      nullable: false
  discriminator:
    propertyName: type
    mapping:
      csv: '#/components/schemas/CsvBlockDTO'
      file: '#/components/schemas/FileBlockDTO'
  oneOf:
  - $ref: '#/components/schemas/CsvBlockDTO'
  - $ref: '#/components/schemas/FileBlockDTO'

CsvBlockDTO:
      allOf:
      - $ref: '#/components/schemas/BlockDTO'
      - required:
        - text
        - type
        type: object
        properties:
          type:
            type: string
            default: csv
            enum:
            - csv
          text:
            type: string
            nullable: false

FileBlockDTO:
      allOf:
      - $ref: '#/components/schemas/BlockDTO'
      - required:
        - fileId
        - type
        type: object
        properties:
          type:
            type: string
            default: file
            enum:
            - file
          fileId:
            type: string
            nullable: false
```

```typescript
// BlockDTO.discriminator
enum BlockDTOType {
  // BlockDTO.discriminator.mapping[key]: BlockDTO.discriminator.mapping[key]
  Csv = 'csv',
  File = 'file'
}

interface AbstractBlockDTO {
  // BlockDTO.discriminator.propertyName
  type: BlockDTOType;
  // BlockDTO.properties.title
  title: string;
}

type BlockDTO = CsvBlockDTO | FileBlockDTO;

type CsvBlockDTO = 
  // CsvBlockDTO.allOf[0]
  AbstractBlockDTO 
  // CsvBlockDTO.allOf[1]
  & {
  // CsvBlockDTO.allOf[1].properties.type
  // > magic should be applied here to understand that 
  //   'type' refers to the 'discriminator' which is 
  //   an enum. Referring to 'magic' since the produced
  //   swagger scheme would make you think it's simply 
  //   an enum with a single value. 
  //
  //   Knowing this property is part of the discriminator we could 
  //   do some reverse lookup to match its value against the 
  //   discriminator.mapping. If the value exists (and refers to this schema)
  //   we take the declared Enum Type. If not we do "something" (create a new type?)
  // [CsvBlockDTO.allOf[1].properties.type]: [BlockDTO.discriminator.mapping.key]
  type: BlockDTOType.Csv;
  // CsvBlockDTO.allOf[1].properties.text
  text: string;
}

// same story as CsvBlock
type FileBlockDTO = 
  // FileBlockDTO.allOf[0]
  AbstractBlockDTO 
  & {
  type: BlockDTOType.File;
  fileId: string;
}
```

If we can make the `discriminator` vs `enum` magic work I think we can solve the missing piece of the puzzle 👼  

--- 

btw @js2me very much appreciate your pro-activeness on this ticket - thanks!

**Comment by js2me** [comment]
@dirkgroenen thanks for this detailed message!  
But what if "discriminator" field doen't have "mapping" field ?   
How it should looks like ?   


Also, using typescript code from your answer we will see the   
```ts
type BlockDTO = CsvBlockDTO | FileBlockDTO;
```   

Which is the only result of the oneOf operation. (If we create the same schema without mapping it will generate the same output typescript code)     

And this part of schema is ignoring as I understand   
![image](https://user-images.githubusercontent.com/16340911/202002357-bceed38f-ef52-437f-9f54-91ad00907d2b.png)

**Comment by js2me** [comment]
> I think what needs to be generated is this, so there is just one enum used.
> 
> ![image](https://user-images.githubusercontent.com/1754392/201966919-5d24fd97-3768-4ef1-a778-a6f0bd274c6f.png)
> 
> But I'm curious to know if that can be generated?

Based on your schema, discriminator field is not needed for you, because it output the same result.   
Current problem with your schemas in the latest swagger-typescript-api - unavailable to resolve circular references

**Comment by js2me** [comment]
Take a look at this example   

```json
"Pet": {
      "type": "object",
      "required": [
        "pet_type"
      ],
      "properties": {
        "pet_type": {
          "type": "string"
        }
      },
      "discriminator": {
        "propertyName": "pet_type",
        "mapping": {
          "cachorro": "#/components/schemas/Dog",
          "cat": "#/components/schemas/Cat"
        }
      }
    },
    "Cat": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Pet"
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "Dog": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Pet"
        },
        {
          "type": "object",
          "properties": {
            "bark": {
              "type": "string"
            }
          }
        }
      ]
    },
```  


With using your solution output typescript code should looks like   

```ts
type AbstractPet = {
  pet_type: string;
}

export type Pet = Cat | Dog

export type Cat = AbstractPet & {
  name?: string;
};

export type Dog = AbstractPet & {
  bark?: string;
};
```

But this is the main problem because **discriminator.mapping** is ignored inside the "Pet" schema   
![image](https://user-images.githubusercontent.com/16340911/202016196-29fdddf4-c165-44bf-aa8e-dd6814eb9030.png)


But based on your swagger schema - pet_type or your "type" field is strictly declared with contstant values

**Comment by js2me** [comment]
But if I will use the current solution with schema above   
```ts

interface AbstractPet {
    pet_type: string;
}

export type Pet = AbstractPet &
  (
    | ({
        pet_type: "cachorro";
      } & Dog)
    | ({
        pet_type: "cat";
      } & Cat)
  );

export type Cat = AbstractPet & {
  name?: string;
};

export type Dog = AbstractPet & {
  bark?: string;
};

const pet: Pet = {
  pet_type: "cat",
  name: "Fluffy",
  bark: "BARK BARK BARK"
}
```

Then we will see that this is correctly typescript code   
![image](https://user-images.githubusercontent.com/16340911/202017502-90d012b7-7469-4817-afd3-4b3f5a2787c2.png)

**Comment by js2me** [comment]
Same thing if we will remove this lines from your swagger schema   

```diff
  "BlockDTO": {
      "required": [
        "title"
      ],
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "nullable": false
        }
      },
      "discriminator": {
        "propertyName": "type",
        "mapping": {
          "csv": "#/components/schemas/CsvBlockDTO",
          "file": "#/components/schemas/FileBlockDTO"
        }
      },
-      "oneOf": [
-        {
-          "$ref": "#/components/schemas/CsvBlockDTO"
-        },
-        {
-          "$ref": "#/components/schemas/FileBlockDTO"
-        }
-      ]
    },
    "CsvBlockDTO": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BlockDTO"
        },
        {
          "required": [
            "text",
            "type"
          ],
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "default": "csv",
              "enum": [
                "csv"
              ]
            },
            "text": {
              "type": "string",
              "nullable": false
            }
          }
        }
      ]
    },
    "FileBlockDTO": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BlockDTO"
        },
        {
          "required": [
            "fileId",
            "type"
          ],
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "default": "file",
              "enum": [
                "file"
              ]
            },
            "fileId": {
              "type": "string",
              "nullable": false
            }
          }
        }
      ]
    }
```


Then we will see good typescript safety solution   

```ts

interface AbstractBlockDto {
    title: string;
}

export type BlockDTO = AbstractBlockDto &
  (
    | ({
        type: "csv";
      } & CsvBlockDTO)
    | ({
        type: "file";
      } & FileBlockDTO)
  );

export type CsvBlockDTO = AbstractBlockDto & {
  /** @default "csv" */
  type: "csv";
  text: string;
};

export type FileBlockDTO = AbstractBlockDto & {
  /** @default "file" */
  type: "file";
  fileId: string;
};

const block: BlockDTO = {
    type:"file",
    fileId: 'asdasd',
    title: 'asdasd',
    text: "test"
}
```
![image](https://user-images.githubusercontent.com/16340911/202018299-f350d4e5-23bd-456d-915b-73c756f28aef.png)

**Comment by js2me** [comment]
Because  

```ts
export type BlockDTO = AbstractBlockDto &
  (
    | (CsvBlockDTO | FileBlockDTO) // <--- THIS IS result of BlockDTO.oneOf
    | ( // BlockDTO.mapping
        | ({
            type: "csv";
          } & CsvBlockDTO)
        | ({
            type: "file";
          } & FileBlockDTO)
      )
  );
```

**Comment by evtk** [comment]
@js2me just checking in to see if all the above is clear to you. Is there anything blocking that we can elaborate on? If we can be of any assistance please let us know. Many thanks!

**Comment by evtk** [comment]
Hey @js2me how are you doing? I see it has been a bit quiet around here and I'm wondering if we can do anything to assist to get things going. We are on the verge of starting big migration of DTO's with the use of OpenAPI so we are definitely looking out for the above feature 👍🏻

**Comment by evtk** [comment]
@js2me we eventually changed the way how we generate the schema, creating the Abstract DTO in there, so there isn't a need for the typescript generator to implement this. 

I'll close the issue.
