### ISSUE TITLE
Broken types for arrays of union types

### ISSUE THREAD

**Issue by jabrandes** [acacode/swagger-typescript-api#49]
The latest release update (version `1.8.1`) introduced array types using the typical brackets-suffixed notation (`${content}[]`). However, the generator seems to produce faulty type definitions when the array is to contain a union of types or a union of enum values. That problem has not occured with previous versions using the `Array<T>` notation. An easy fix respecting the intentions of release `1.8.1` may be to put the content type inside parentheses to which the brackets-suffix can be applied.

### Screenshots of the problem
Original Swagger definition:
![image](https://user-images.githubusercontent.com/16663164/83262668-b1142600-a1bd-11ea-8ebd-0c0439f61e2a.png)

Generated code: `1.8.1` generated type to the left, pre-`1.8.1` generated type to the right
![image](https://user-images.githubusercontent.com/11928969/83256047-00ecf000-a1b2-11ea-80a5-c91c8dca504c.png)

**Comment by js2me** [comment]
@jabrandes Hello! Thanks for the issue report!  
I will fix it right now!

**Comment by jabrandes** [comment]
@js2me Thanks a lot! :smiley:

**Comment by js2me** [comment]
It should be fixed in release 1.8.2 🙂
