### ISSUE TITLE
Update the version of "eta" to prevent a high severity vulnerability

### ISSUE THREAD

**Issue by amielucha** [acacode/swagger-typescript-api#491]
According to npm audit all versions of eta <2.0.0 have a high severity vulnerability.

[Eta vulnerable to Code Injection](https://github.com/advisories/GHSA-mf6x-hrgr-658f) via templates rendered with user-defined data.

Update the dependency to resolve the issue.

**Comment by juliusBaranauskas** [comment]
Fix already released (#490) a while ago. Issue can be closed
