### ISSUE TITLE
Project is ABANDONED?

### ISSUE THREAD

**Issue by inomn** [acacode/swagger-typescript-api#535]

**Comment by emilecantin** [comment]
@inomn There was a release last week, what makes you think it's abandoned?

**Comment by inomn** [comment]
> @inomn There was a release last week, what makes you think it's abandoned?

@emilecantin MAYBE the fact that I posted this on May 31 and there were (and still) a lot of issues\PRs without replies?

**Comment by inomn** [comment]
anyway, clearly no
