### ISSUE TITLE
Custom Templates

### ISSUE THREAD

**Issue by andrefilimono** [acacode/swagger-typescript-api#54]
Hi! 
It'd be cool to be able to provide custom templates directory to this tool in order to tweak templates or just leverage the parser to generate custom models or something like that. It's all only about yet another argument e.g. `--templates`.

Would it be of your interest if I made a PR with this feature?

**Comment by js2me** [comment]
@andrefilimono yeah! That's a great idea! Please open a PR with this feature if you can :)

**Comment by js2me** [comment]
@andrefilimono please create an own branch from the `next` branch

**Comment by andrefilimono** [comment]
Okay, hopefully I'll do it by the end of the week :)

**Comment by alesdvorakcz** [comment]
this would be great feature. thumbs up :)

**Comment by js2me** [comment]
@alesdvorakcz this feature has been added in 1.10.0 version. Thanks for your pull request !
