### ISSUE TITLE
swagger-typescript-api no longer ouputting `<Tag>Routes` after upgrade to 13.0.0

### ISSUE THREAD

**Issue by rcbevans** [acacode/swagger-typescript-api#553]
I am doing chores to bump packages and after upgrading swagger-typescript-api to 13.0.0 no Route types seem to be getting generated.

The command line I'm using to generate the types is

```
swagger-typescript-api -p ./api.spec.yaml -o ./src/Api/ -r --union-enums --add-readonly --route-types --extract-request-params --extract-request-body --extract-response-body --extract-response-error --modular --disableProxy --clean-output --sort-types --module-name-first-tag --axios
```

I didn't change this command when upgrading, and I don't see anything in the changelog to suggest that these arguments have changed behavior.

**Comment by kevbost** [comment]
I saw this happen too, had to downgrade to 12.0.4 which is causing it's own set of issues for me evaluating this package.

**Comment by rcbevans** [comment]
Any update on this?  I tried the latest version yesterday and route types still aren't being generated.

**Comment by rcbevans** [comment]
It's unfortunate that this is still an issue.
