### ISSUE TITLE
String enums

### ISSUE THREAD

**Issue by alesdvorakcz** [acacode/swagger-typescript-api#58]
Hello,
Is there any way how to easily change how enums are generated?

Shema
```js
DayOfWeek: {
  enum: [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday"
  ],
  type: "string"
},
```

Instead of this
```js
export enum DayOfWeek {
  Sunday = "Sunday",
  Monday = "Monday",
  Tuesday = "Tuesday",
  Wednesday = "Wednesday",
  Thursday = "Thursday",
  Friday = "Friday",
  Saturday = "Saturday",
}
```

I would like to have this
```js
export type DayOfWeek = 
  | "Sunday" 
  | "Monday" 
  | "Tuesday" 
  | "Wednesday" 
  | "Thursday" 
  | "Friday" 
  | "Saturday";
```

Thanks in advance

**Comment by js2me** [comment]
Hello @alesdvorakcz ! :)   
Thanks for this issue, I think it looks like the feature request.  
I will add the specific CLI flag (something like `--onion-enums`) to swagger-typescript-api tool.

**Comment by js2me** [comment]
It will be in the next major release 2.0 (branch v2)

**Comment by alesdvorakcz** [comment]
Perfect, Thanks!
Any ETA? Is there something I can help with?

**Comment by js2me** [comment]
@alesdvorakcz is that very needed for you?   
If it is then I can add it in the next release (2-3 hours) (with custom templates)

**Comment by js2me** [comment]
version 2.0.0 will be released at the end of the next week

**Comment by alesdvorakcz** [comment]
Dont worry about it, I can wait.

**Comment by js2me** [comment]
@alesdvorakcz this feature has been added in 1.10.0 version. Thanks for this issue!

**Comment by Akronae** [comment]
Is there any way to handle one of enum or string?
Like `datasource: MyEnum | (string & {})`

```json
{
  "properties": {
    "datasource": {
      "oneOf": [
        {
          "enum": ["a", "b", "c"]
        },
        {
          "type": "string"
        }
      ]
    }
  }
}
```

Currently the generated code is
`datasource: MyEnum | string`
