### ISSUE TITLE
All properties are always optional

### ISSUE THREAD

**Issue by alesdvorakcz** [acacode/swagger-typescript-api#59]
Hi,
I am wondering why from this schema:
```js
Manufacturer: {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid"
    },
    created: {
      type: "string",
      format: "date-time"
    },
    modified: {
      type: "string",
      format: "date-time"
    },
    name: {
      type: "string",
      nullable: true
    },
    identificationNumber: {
      type: "string",
      nullable: true
    }
  },
  additionalProperties: false
},
```

I am getting this:
```js
export interface Manufacturer {
  id?: string;
  created?: string;
  modified?: string;
  name?: string | null;
  identificationNumber?: string | null;
}
```

instead of this:
```js
export interface Manufacturer {
  id: string;
  created: string;
  modified: string;
  name: string | null; //or name?: string;
  identificationNumber: string | null;  //or identificationNumber?: string;
}
```

Am I doing something wrong?

**Comment by js2me** [comment]
Hello @alesdvorakcz ! Can you say the version of usage schema ?  (3.0, 3.1, 2.0)   
If you are using 2.0 version then you should add the list of required properties like in this schema:  
https://github.com/acacode/swagger-typescript-api/blob/master/tests/schemas/v2.0/authentiq.json#L870

**Comment by js2me** [comment]
Same thing you should do with 3.0+ versions:  
(example with Open API 3.0)  
https://github.com/acacode/swagger-typescript-api/blob/master/tests/schemas/v3.0/personal-api-example.json#L134

**Comment by alesdvorakcz** [comment]
You are right, its what I am missing in my schema (3.0)

Thank you for fast response and amazing project!
