### ISSUE TITLE
Using fetch client returned null data, while using axios client worked as expected

### ISSUE THREAD

**Issue by teddyfullstack** [acacode/swagger-typescript-api#673]
When using the fetch client, I noticed that only when I call `json()` does the response data appear in the Devtools' Network tab. However, the typed data object is still null:

```ts
const result = await client.getBoard({
    boardType: "TOP",
  });
// result.data is null
const jsonData = await result.json() // jsonData contains the server response, but its type is "any"
return result.data; // result.data is still null, but it is what I want because it is strongly typed!
```

Switching to the axios client fixed the issue:

```
swagger-typescript-api --axios ...
```

```ts
const result = await client.getBoard({
    boardType: "TOP",
  });
return result.data; // data is returned without calling json()
```

I hope this issue report can help improve the library, although it is already so great. If there is any chance the issue is on our server's end, feel free to close this 👌

**Comment by alande-amorim** [comment]
@teddyfullstack that's the default behavior when using the fetch client. If you don't want to use `await result.json()` then set the `baseApiParams: {format: 'json'}`

**Comment by teddyfullstack** [comment]
Oh adding `baseApiParams: {format: 'json'}` did the trick. It's not really obvious to find in the docs anyway. Thank you for your support 💯
