### ISSUE TITLE
Can provide ability to generate from swagger JSON directly not from a file?

### ISSUE THREAD

**Issue by JennieJi** [acacode/swagger-typescript-api#69]

**Comment by JasonLandbridge** [comment]
That already work from scripts in the package.json:
```
"scripts":
{
	"generate-ts": "npx swagger-typescript-api -p http://localhost:5000/swagger/v1/swagger.json -o ./src/types/dto/api/ -n mainApi.ts",
},
```

**Comment by JennieJi** [comment]
Hi @JasonLandbridge , I am talking about Input the j object to the function exposed. The reason why I ask this is because I am building a cli tool with this lib and the swagger json require some preprocessing and I don’t want to write into a file first before continue

**Comment by JasonLandbridge** [comment]
Ah sorry, I can't help you with that. Maybe the maintainer of this repository can help with that

**Comment by js2me** [comment]
This feature added in 1.12.0 version!  
Thank you @JennieJi

**Comment by JennieJi** [comment]
Thank you @js2me
