### ISSUE TITLE
Add extra maintainer?

### ISSUE THREAD

**Issue by JasonLandbridge** [acacode/swagger-typescript-api#697]
Hi @js2me, 

I see you might be too busy to maintain this project due to the number of open issues and pull request. So I would like to volunteer in maintaining this project, if you would like. For others reading this, if you're interested in volunteering as well then leave a comment down below.

Thanks for all the hard work in this awesome project!

**Comment by AshotN** [comment]
@JasonLandbridge if @js2me doesn't respond, would you be open to forking the project?

**Comment by JasonLandbridge** [comment]
@AshotN , I would honestly prefer if this repo can be maintained instead of a fork due to the extra overhead. Let's see if @js2me responds and then it might need to be forked if he doesn't

**Comment by smorimoto** [comment]
I believe this is not a issue for now!
