### ISSUE TITLE
Remove const enum from default template

### ISSUE THREAD

**Issue by alievrenkut** [acacode/swagger-typescript-api#73]
Hi,

I really liked your library but I have an issue with a React project. Create React App project does not support "const enums" because of Babel. You can look at link for more information: https://github.com/facebook/create-react-app/issues/5681

Could you remove "const" modifier from "enum" at client.mustache?

P.S: I know that in a ideal world I should create an issue at Create React App project but it looks like they will or can not fix it. So I create here.

**Comment by js2me** [comment]
@alievrenkut Hello, ok will do that at next release!

**Comment by js2me** [comment]
`const enum` should be removed in 1.12.0
