### ISSUE TITLE
Question: Is there a way to not add List at end of method name

### ISSUE THREAD

**Issue by alievrenkut** [acacode/swagger-typescript-api#74]
I have a spring rest endpoint like:
```
@RestController
@RequestMapping("/util")
public class UtilResource {

    @Transactional
    @GetMapping
    @RequestMapping("/generator")
    public void generate(@RequestParam("count") int count) {
```
It generates below Typescript code but I do not want List at end of method name. Is there way to prevent that?

```
util = {
    /**
     * @name generatorList
     * @request GET:/util/generator
     */
    generatorList: (query?: { count?: number }, params?: RequestParams) =>
      this.request<any, any>(`/util/generator${this.addQueryParams(query)}`, "GET", params),
  };
```

**Comment by js2me** [comment]
Hello, @alievrenkut!
Currently not.

**Comment by js2me** [comment]
Currently with `4.0.0` version you can use `--templates` option and fully customize all codegenerator   
Attached the template codeline based on this issue:   
https://github.com/acacode/swagger-typescript-api/blob/master/templates/default/route-name.eta#L18   

Hope it will you
