### ISSUE TITLE
Code formatting broken since 13.0.5

### ISSUE THREAD

**Issue by pebo** [acacode/swagger-typescript-api#780]
The https://github.com/acacode/swagger-typescript-api/pull/717 PR breaks code formatting if the prettier config file is not located in the current working directory.

From [v9.0.0](https://github.com/cosmiconfig/cosmiconfig/releases/tag/v9.0.0) the cosmiconfig package no longer searches upwards for prettier config by default. To enable the old behavior the `searchStrategy` `global` should be used.

**Comment by NiiMER** [comment]
Any update on this from The @ Contributors ??

**Comment by NiiMER** [comment]
Would it be ready in the next version @smorimoto ?

**Comment by smorimoto** [comment]
@pebo @NiiMER https://github.com/acacode/swagger-typescript-api/releases/tag/13.0.7
