### ISSUE TITLE
Async securityWorker

### ISSUE THREAD

**Issue by alievrenkut** [acacode/swagger-typescript-api#82]
Hi, Could you change template code so that securityWorker will be async function. I need this so that I can check my JWT token is expired or not and update it if it is expired. I can not do this with current securityWorker. 

I suggest you to change current template to below
```

type ApiConfig<SecurityDataType> = {
  baseUrl?: string;
  baseApiParams?: RequestParams;
  securityWorker?: (securityData: SecurityDataType) => Promise<RequestParams>;
};
  
  public request = async <T = any, E = any>(
    path: string,
    method: string,
    { secure, ...params }: RequestParams = {},
    body?: any,
    bodyType?: BodyType,
    secureByDefault?: boolean,
  ): Promise<T> =>{
    const securityRequestParams = (secureByDefault || secure) && (await this.securityWorker(this.securityData));
    return fetch(`${this.baseUrl}${path}`, {
      // @ts-ignore
      ...this.mergeRequestOptions(params, securityRequestParams),
      method,
      body: body ? this.bodyFormatters[bodyType || BodyType.Json](body) : null,
    }).then(async (response) => {
      const data = await this.safeParseResponse<T, E>(response);
      if (!response.ok) throw data;
      return data;
    });
  }
```

**Comment by js2me** [comment]
Hello @alievrenkut !   
Thanks for this issue, update template at the next major release.

**Comment by js2me** [comment]
Hello @alievrenkut !   
I think it's better is to update http client mustache template and make the ability to modify `ApiConfig` interface   
![image](https://user-images.githubusercontent.com/16340911/97398054-94f6eb00-18fb-11eb-89be-3dac63631b13.png)

**Comment by js2me** [comment]
![image](https://user-images.githubusercontent.com/16340911/97399334-059f0700-18fe-11eb-9ef9-1f13dc12558a.png)

**Comment by js2me** [comment]
Take a look at the custom `client.mustache` template:   
https://github.com/acacode/swagger-typescript-api/blob/next/tests/spec/templates/spec_templates/client.mustache   
And generated schema:   
https://github.com/acacode/swagger-typescript-api/blob/next/tests/spec/templates/schema.ts

**Comment by js2me** [comment]
In general you can modify `client.mustache` template and add async `securityWorker` this in the release 2.0.0
