### ISSUE TITLE
[BUG] [13.0.19] TypeError: e.commands is not iterable

### ISSUE THREAD

**Issue by teyyubismayil** [acacode/swagger-typescript-api#880]
Folllowing command fails with `TypeError: e.commands is not iterable` error at version `13.0.19`:

`npx swagger-typescript-api --extract-request-params --axios -p ./swagger.json -n ./service.ts`

**Comment by 0xyy** [comment]
same issue here

**Comment by mpoweredo** [comment]
same situation in my project

**Comment by 0xyy** [comment]
I found temporary solution for this, just run a command with specific version for example 
`npx swagger-typescript-api@13.0.16 ...`

**Comment by danpoletaev** [comment]
> I found temporary solution for this, just run a command with specific version for example `npx swagger-typescript-api@13.0.16 ...`

Or you can downgrade to 13.0.16 and it works

**Comment by serrg** [comment]
Same issue here, confirmed that downgrading to `13.0.16` fixed it

**Comment by 7architect** [comment]
same

```bash
pnpx swagger-typescript-api@13.0.16 -p "$TEMP_FILE" -o ./src/shared/generated -n api.ts \
    --extract-request-params \
    --extract-request-body \
    --extract-response-body \
    --extract-enums \
    --route-types \
    --axios \
    --module-name-first-tag \
    --single-http-client \
    --enum-names-as-values \
    --sort-routes \
    --sort-types
```

**Comment by 7architect** [comment]
versions upper than 13.0.16 also corrupted

**Comment by ahmadbakhshi** [comment]
In my case, it cased by same operation Id.
After updating my operation ids with unique keys, it worked fine for me

**Comment by xavierbloemen** [comment]
@smorimoto Thanks for the fix!

**Comment by ahmadbakhshi** [comment]
Everything is working for me too.
Thank you @smorimoto

**Comment by smorimoto** [comment]
We've been gradually making changes to migrate the codebase to TypeScript, but in the process we've broken some things. Sorry for the bother 😑

**Comment by teyyubismayil** [comment]
Thanks for the fix @smorimoto!
