### ISSUE TITLE
structuredClone is not defined

### ISSUE THREAD

**Issue by taurus-prog** [acacode/swagger-typescript-api#883]
ReferenceError: structuredClone is not defined

**Comment by smorimoto** [comment]
Are you really using Node.js 17 or later?
https://nodejs.org/api/globals.html#structuredclonevalue-options

However, the minimum requirement for this project is Node.js 18.
https://github.com/acacode/swagger-typescript-api/blob/544216da3a15067cece294e8eeddf0a09f60a87e/package.json#L78
