### ISSUE TITLE
name.includes is not a function

### ISSUE THREAD

**Issue by noel879633754** [acacode/swagger-typescript-api#98]
![image](https://user-images.githubusercontent.com/47893069/102738760-0dbb7600-4386-11eb-93b8-e5fa66d392f7.png)

**Comment by js2me** [comment]
Hello @noel879633754 !   
Got your problem, fix it today!

**Comment by js2me** [comment]
@noel879633754  can you share swagger schema or enums from schema ?

**Comment by js2me** [comment]
Should be fixed at 3.1.1!   
Thanks for this issue!

**Comment by js2me** [comment]
@noel879633754 reopen if you still get this problem
